### PR TITLE
Tests no longer target the TDS at remotetest.unidata.ucar.edu

### PR DESCRIPTION
**Pull request by cwardgar**
* Instead, they target the embedded TDS that's launched in `:it:test`. Some test classes needed to be moved into `:it` to make that possible. Had to move around some datasets and tweak some paths as well to keep tests passing.
* `TestSSH`, `TestTomcatAuth`, and `TestByteRange` were improved to allow execution within Jenkins and Travis. Previously, they had to be run manually from IntelliJ.
* Removed `NeedsExternalResource` annotation from every test I could. More pruning to come in the future.
* Added `NeedsCdmUnitTest` to a couple of classes that (sneakily) require it.
* `:it:appRun` no longer requires `:it:processTestResources` to be run first.

With this PR, we no longer have any dependence on remotetest.unidata.ucar.edu that I'm aware of. @DennisHeimbigner I'd like you to take a look at my changes to `TestSSH`, `TestTomcatAuth`, and `TestByteRange` and tell me if they're okay.

### CODE REVIEW

**Comment by cwardgar** [comment]
Oh, also please review my changes to `TestDir`. After my changes, the `isTravisOrJenkins` static variable didn't seem necessary any more, so I nuked it. But maybe I'm wrong.

**Comment by cwardgar** [comment]
After merging #741 and rebasing, this now passes Travis! Cool. #214 and #637 remain problems, but I think Dennis is working on that in a separate branch.

@DennisHeimbigner Is this ready to go in?

**Comment by DennisHeimbigner** [comment]
Which 'this' are you referring to?

**Comment by cwardgar** [comment]
This PR. Can you take a look and see if it's ready to be merged?

**Pull request merged**
