### PR TITLE
thredds-parent Maven BOM publication (fixes #323)

### LINKED ISSUE #323: Generate thredds-parent BOM
From #310.

These pages should be helpful:
http://stackoverflow.com/questions/17281927/how-to-make-gradle-generate-a-valid-pom-xml-file-at-the-root-of-a-project-for-ma
https://discuss.gradle.org/t/how-can-i-publish-a-custom-pom-produced-by-a-custom-task/5061

### PR DESCRIPTION
**Pull request by cwardgar**
I imported the new BOM into [geotiff-iosp](https://github.com/USGS-CIDA/geotiff-iosp) and was able to build successfully, so I'm pretty confident I got this right. I'd still like to here from @tkunicki, but I don't think it's necessary to delay merging in the PR.

We now have unit tests covering (some of) our build logic! Cool, right? Gradle and Groovy are like magic, dude.

### CODE REVIEW

**Comment by cwardgar** [comment]
Actually, hold off on this one. The new :buildSrc project isn't being picked up in Gradle's test reports. Interestingly, it is being reported in Jenkins.

**Comment by lesserwhirls** [comment]
Sounds good - just let me know when it's ready @cwardgar (a.k.a. gradle and groovy master!)

**Comment by tkunicki** [comment]
I will look at this today.

**Comment by cwardgar** [comment]
Okay, :buildSrc test results and coverage are being reported everywhere. This is okay to merge.

**Pull request merged**
