### PR TITLE
Check links when building docs (take 2)

### PR DESCRIPTION
**Pull request by cwardgar**
Continued from #500. This is on a Unidata branch, so we should all be able to make changes. Thanks for moving this over, @dopplershift!

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Closing in favor of a gradle solution - see Unidata/thredds#764

**Comment by dopplershift** [comment]
NOOOOO! My hard work! 😀 

Seriously, using code someone else has to maintain always better.

Oh wait--I'm not sure you should close this out completely. There's a bunch of fixed links in this PR as well.

**Comment by lesserwhirls** [comment]
I'll make sure to grab them for the new docs in kramdown. Thanks @dopplershift!

**Comment by cwardgar** [comment]
I'm gonna go out on a limb and conclude that there's not a whole lot of value in keeping this open any longer.

**Pull request closed without merging**
