### PR TITLE
Grib coord cleanup2: 

### PR DESCRIPTION
**Pull request by JohnLCaron**
Remove old coordinate cruft from ucar.nc2.grib package

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Wait on this one until the previous is through.

**Comment by JohnLCaron** [comment]
ok ready to go.

**Comment by JohnLCaron** [comment]
compileTest ok now. User error I think.

**Comment by lesserwhirls** [comment]
It looks like this PR includes the commits from Unidata/thredds#1267? I'll merge this one in and close the other.

**Pull request merged**
