### PR TITLE
Resolves Unidata/thredds#896

### PR DESCRIPTION
**Pull request by cofinoa**
The thredds catalog element timeCoverage can accept a calendar attribute.

### CODE REVIEW

**Comment by cwardgar** [comment]
@cofinoa Thanks for the contribution! I think we should add a test for this before merging it in.

**Comment by lesserwhirls** [comment]
We will also need to update the xsd ([InvCatalog.1.2.xsd](https://github.com/Unidata/thredds/blob/b731bcb45b6e10b7e6102e97a9ef35e9fef43c93/cdm/src/main/resources/resources/thredds/schemas/InvCatalog.1.2.xsd)). Since 5.0 isn't released yet, I think it is ok to keep the version as-is.

**Comment by cofinoa** [comment]
@cwardgar do you want to me to add the tests? I'm not experienced on that, but if you provide to me some "clues" I can try. what is the next step?

@lesserwhirls do you think we can integrate this onto InvCatalog.1.0.7.xsd too? and what about TDS4.6?

**Comment by cwardgar** [comment]
Well, it turns out that we're not testing `timeCoverageType` at all currently, so adding something for your new `calendar` attribute wouldn't be as easy as I hoped. We really need to overhaul our catalog testing, with a goal of 100% coverage of the various capabilities.

But I won't make you wait until we've done that; your PR looks good to go in now. It's pretty simple after all.

@lesserwhirls So what is the difference between `InvCatalog.1.0.7.xsd` and `InvCatalog.1.2.xsd`? Is 1.0.7 for TDS 4.6 and 1.2 for TDS 5.0? Do you think we should add the `calendar` attribute to both?

**Comment by cwardgar** [comment]
This PR is superseded by #1002. Thanks for getting this feature rolling, @cofinoa.

**Pull request closed without merging**
