### PR TITLE
5.0.0

### PR DESCRIPTION
**Pull request by JohnLCaron**
proto3, cdmRemote, coverage integration.

### CODE REVIEW

**Comment by lesserwhirls** [comment]
I've also re-rendered the docs and published them on the web:

http://www.unidata.ucar.edu/software/thredds/v5.0/adoc_convert/tds/TDS.html

http://www.unidata.ucar.edu/software/thredds/v5.0/adoc_convert/netcdf-java/documentation.html

**Comment by JohnLCaron** [comment]
thanks for rendering html.
can we get doug to make a pass at getting decent css?

looking at eg:

http://www.unidata.ucar.edu/software/thredds/v5.0/adoc_convert/netcdf-java/reference/stream/CdmRemote.html

1) no shading on blocks (<pre>)
2) no lines in tables
3) [source,xml] in red ?

etc

probably need some iterations with him, so would be good to get that
started.

thanks

**Comment by lesserwhirls** [comment]
Is this better in terms of the code?

http://www.unidata.ucar.edu/software/thredds/v5.0/adoc_convert/tds/UpgradingTo5.html

**Comment by JohnLCaron** [comment]
code blocks still not delimited

**Comment by lesserwhirls** [comment]
You mean like a shaded box around them? Like here:
http://www.unidata.ucar.edu/software/thredds/current/tds/UpgradingTo4.6.html

**Comment by JohnLCaron** [comment]
yes or here:

https://github.com/JohnLCaron/thredds/blob/5.0.0/docs/website/tds/UpgradingTo5.adoc

**Comment by lesserwhirls** [comment]
Ah, ok - that's the github.com css doing that. That will probably be controlled in a custom css file. Maybe @ddirks can join us at our meeting tomorrow (10:30 am)?

**Comment by ddirks** [comment]
I'm in an EarthCube Office meeting tomorrow 9-11am. How long is your
thredds meeting?

-=DD=-


On Wed, Oct 28, 2015 at 3:25 PM, Sean Arms <notifications@github.com> wrote:

> Ah, ok - that's the github.com css doing that. That will probably be
> controlled in a custom css file. Maybe @ddirks <https://github.com/ddirks>
> can join us at our meeting tomorrow (10:30 am)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unidata/thredds/pull/254#issuecomment-151996132>.
>



-- 
Douglas Dirks
Unidata Community Services
ddirks@ucar.edu <ddirks@unidata.ucar.edu>  *  303-497-8657

**Comment by lesserwhirls** [comment]
Oh, we'll still be there I'm sure.

**Pull request merged**
