### PR TITLE
Cleanup grib tests

### PR DESCRIPTION
**Pull request by JohnLCaron**
Grib1 tests, pass 1.

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Pass 1, focusing on ucar.nc2.grib.grib1.

**Comment by JohnLCaron** [comment]
Ok, Im going to let stop on this branch now, so ready to go assuming tests are ok....

**Comment by lesserwhirls** [comment]
Looks like we have 5 failures on Travis:

~~~bash
ucar.nc2.grib.grib2.TestPds61 > checkNumberOfTimeRanges FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at ucar.nc2.grib.grib2.TestPds61.openTestFile(TestPds61.java:40)
~~~

~~~bash
ucar.nc2.grib.grib2.TestPds61 > checkModelVersionDate FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at ucar.nc2.grib.grib2.TestPds61.openTestFile(TestPds61.java:40)
~~~

~~~bash
ucar.nc2.grib.grib2.TestPds61 > checkEndOfOverallIntervalDate FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at ucar.nc2.grib.grib2.TestPds61.openTestFile(TestPds61.java:40)
~~~

~~~bash
ucar.nc2.grib.grib2.TestPds61 > checkTypeOfGeneratingProcess FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at ucar.nc2.grib.grib2.TestPds61.openTestFile(TestPds61.java:40)
~~~

~~~bash
ucar.nc2.grib.grib2.TestPds61 > checkPdsBasic FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at ucar.nc2.grib.grib2.TestPds61.openTestFile(TestPds61.java:40)
~~~

~~~bash
ucar.nc2.grib.TestGribIndexProto > testOpen[grib1.proto3.gbx9] STANDARD_OUT
    [1;31m[23:29:11.644 ERROR ucar.nc2.grib.grib1.Grib1Index][0;39m GribIndex failed on ../grib/src/test/data/index/grib1.proto3.gbx9
    com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: records[0].header, records[0].gdsIdx
    	at com.google.protobuf.UninitializedMessageException.asInvalidProtocolBufferException(UninitializedMessageException.java:81)
    	at com.google.protobuf.AbstractParser.checkMessageInitialized(AbstractParser.java:72)
    	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:196)
    	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
    	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)
    	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
    	at ucar.nc2.grib.grib1.Grib1IndexProto$Grib1Index.parseFrom(Grib1IndexProto.java:1915)
    	at ucar.nc2.grib.grib1.Grib1Index.readIndex(Grib1Index.java:120)
    	at ucar.nc2.grib.TestGribIndexProto.testOpen(TestGribIndexProto.java:57)
<SNIP>
~~~

~~~bash
ucar.nc2.grib.TestGribIndexProto > testOpen[grib2.proto3.gbx9] STANDARD_OUT
    [1;31m[23:29:11.733 ERROR ucar.nc2.grib.grib2.Grib2Index][0;39m GribIndex failed on ../grib/src/test/data/index/grib2.proto3.gbx9
    com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: records[0].header, records[0].gdsIdx, records[0].drsTemplate, records[0].bmsIndicator, records[0].ids.subcenter_id, records[0].ids.local_table_version, records[1].header, records[1].drsTemplate, records[1].bmsIndicator, records[1].ids.subcenter_id, records[1].ids.local_table_version, records[2].header, records[2].drsTemplate, records[2].bmsIndicator, records[2].ids.subcenter_id, records[2].ids.local_table_version
    	at com.google.protobuf.UninitializedMessageException.asInvalidProtocolBufferException(UninitializedMessageException.java:81)
    	at com.google.protobuf.AbstractParser.checkMessageInitialized(AbstractParser.java:72)
    	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:196)
    	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
    	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)
    	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index.parseFrom(Grib2IndexProto.java:4139)
    	at ucar.nc2.grib.grib2.Grib2Index.readIndex(Grib2Index.java:124)
    	at ucar.nc2.grib.TestGribIndexProto.testOpen(TestGribIndexProto.java:61)
<SNIP>
~~~

**Comment by lesserwhirls** [comment]
Looks like there are four new failures on Jenkins:


* ucar.nc2.ft.coverage.TestCoverageFMRCnonOrthogonal.testRegularTime2D
* thredds.server.catalog.TestDataFactory.testOpenFromDataFactory[thredds:http://localhost:8081/thredds/catalog/grib.v5/NDFD/CONUS_5km/catalog.xml#grib.v5/NDFD/CONUS_5km/TwoD]
* thredds.server.catalog.TestDataFactory.testOpenFromDataFactory[thredds:http://localhost:8081/thredds/catalog/rdaTest/ds094.2_dt/catalog.xml#rdaTest/ds094.2_dt/GaussLatLon_880X1760-0p00N-180p00E]
* thredds.server.cdmrf.TestGribFmrcRegularTime.testCoverageDataset2D

**Comment by lesserwhirls** [comment]
Strike that, those were "new" on your project on Jenkins, but not new as of the last run of 5.0...my bad. Looks like we're good to merge this one in.

**Pull request merged**
