### PR TITLE
Modifier order

### PR DESCRIPTION
**Pull request by JohnLCaron**
grib cleanup - standardize modifier order to follow JLS

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Does this PR include the changes from Unidata/thredds#1222?

**Comment by JohnLCaron** [comment]
Yes. If you want I can rebase once 1222 is accepted.

**Comment by lesserwhirls** [comment]
Ok, cool - since the changes from 1222 are also on this one, so we can just close out 1222 and go with this one (one review instead of two).

**Comment by lesserwhirls** [comment]
Out of curiosity, are you applying a code style (like the [Google java style](https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml))?

**Comment by JohnLCaron** [comment]
No, just IntelliJ Inspections.

**Pull request merged**
