### PR TITLE
ToolsUI cleanup

### PR DESCRIPTION
**Pull request by JohnLCaron**
Mostly minor fixes from IntelliJ code inspections.
Restored FeatureScanOpPanel, with minor fix that was throwing an Exception. Not sure how it got removed, but seems to be a one-off.

### CODE REVIEW

**Comment by msdsoftware** [comment]
As many changes as I was making a few months go into ToolsUI to break code out into separate classes, _stuff_ may have happened.

**Comment by JohnLCaron** [comment]
yeah, stuff happens ;^)
thanks for your help cleaning it up.

**Comment by JohnLCaron** [comment]
Ok, enough ui for now.

**Comment by msdsoftware** [comment]
Just noticing the indenting changes in OpPanel. Is that an IntelliJ thing to have indents be 2 chars rather than 4?

Asking because I had discovered in the past that indenting of various classes was 2 chars instead of the 4 that I expected.

**Pull request merged**
