### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by lesserwhirls**
Update a few dependencies and remove old godiva2 files. Will need to run on Jenkins just to be sure about the chronicle-map upgrade.

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Did I break gretty? It looks like none of our integrations tests ran. @cwardgar?

**Comment by cwardgar** [comment]
This is definitely a problem with the chronicle-map upgrade. When testing your branch locally (with `./gradlew -i :tds:appRun`), I'm getting errors like these in `tds/src/test/content/thredds/logs/catalogInit.log`:
```
DatasetTrackerChronicle failed on '/Users/cwardgar/dev/projects/thredds2/tds/src/test/content/thredds/cache/catalog/chronicle.datasets.dat.1', delete catalog cache and reload 
java.lang.IllegalStateException: Key size in serialized form must be configured in ChronicleMap, at least approximately.
Use builder.averageKey()/.constantKeySizeBySample()/.averageKeySize() methods to configure the size
```

**Comment by lesserwhirls** [comment]
Ok, cool - I'll take a look.

**Comment by lesserwhirls** [comment]
Ok, let's try this.

**Comment by lesserwhirls** [comment]
Started a run on jenkins.

**Comment by lesserwhirls** [comment]
I got all excited when the tests on Jenkins passed with *zero* errors, but then realized that I wasn't running any tests...running again, this time, with tests.

**Comment by lesserwhirls** [comment]
Ok, no new failures. Should be good to go.

**Pull request merged**
