### PR TITLE
Fix VectorLayer components look up in wms server

### PR DESCRIPTION
**Pull request by bielfrontera**
Fixes a bug searching the two components in a vector layer request.
We have found this problem after adding QC flags to our dataset.

This is our scenario:

We have variables with these standard names:
- eastward_sea_water_velocity
- eastward_sea_water_velocity status_flag
- northward_sea_water_velocity
- northward_sea_water_velocity status_flag

It follows the CF-conventions (see
http://cf-pcmdi.llnl.gov/documents/cf-conventions/1.6/cf-conventions.html#flags )

In this scenario, sea_water_velocity is listed as an available layer of the dataset.
But when this layer is requested, we get this exception:
    uk.ac.rdg.resc.ncwms.exceptions.LayerNotDefinedException:
    The layer "sea_water_velocity" is not provided by this server

The problem was getting the layer components. The function isComponent was returning
both eastward_sea_water_velocity and eastward_sea_water_velocity status_flag as
sea_water_velocity components.

We have modified isComponent function in order to return only the variables which
match with the layer requested. With these changes, ThreddsDataset.getLayerComponents
is compatible with what WMSUtils.findVectorLayers does. According to this, a better
solution would be to move this functionality to WMSUtils, so both functions would be
in the same package.

Note: you can see this problem at
http://thredds.socib.es/thredds/godiva2/godiva2.html?server=http://thredds.socib.es/thredds/wms/hf_radar/hf_radar_ibiza-scb_codarssproc001/L1/2013/dep0001_hf-radar-ibiza_scb-codarssproc001_L1_2013-12.nc

### CODE REVIEW

**Comment by kristiansebastian** [comment]
Hi,

This fix hasn't be added to the release 4.6.1 as you can see https://github.com/Unidata/thredds/blob/v4.6.1/tds/src/main/java/thredds/server/wms/ThreddsDataset.java

Please, Could you add the fix to the next release?

Best regards,

Kristian

**Comment by rsignell-usgs** [comment]
@ethanrd and @lesserwhirls this is a tiny fix, can you guys merge it?

**Comment by lesserwhirls** [comment]
I think we can do this. Not sure how this fell through the cracks, though. Would it be possible to rebase this on master?

**Comment by rsignell-usgs** [comment]
@joanpau, would one of you SOCIB guys be willing to so this?

**Comment by dopplershift** [comment]
Wow, really *not good* that this PR was closed without comment.

**Comment by rsignell-usgs** [comment]
After getting this one merged, I'll try to help get some of the other SOCIB ncWMS improvements submitted.    They've got a bunch of additional styles that are cool, and those new WMS styles allow them to do nifty stuff like this:
http://apps.socib.es/Leaflet.TimeDimension/examples/example6.html

and more cool client examples using TDS WMS services here:
http://apps.socib.es/Leaflet.TimeDimension/examples/

**Comment by lesserwhirls** [comment]
Just remember that all of the ncWMS stuff will be different in TDS v5.

**Comment by rsignell-usgs** [comment]
Who is the point person on ncWMS now that Marcos is gone?

**Comment by lesserwhirls** [comment]
I suppose that'd be me at this point.

**Comment by joanpau** [comment]
We just rebased the fix onto the master branch.
Please note that, as stated in the commit message and in the description of the pull request,
it would be better to move the modified function to the `WmsUtils` package in ncWMS.
I do not know, however, if it is worth to do it now if release 5.0.0 is moving to ncWMS2.

**Comment by JohnLCaron** [comment]
Not sure why I closed this 2 years ago, but I agree it was a mistake.

**Pull request merged**
