### PR TITLE
Added some mac related fixes to toolsUI

### PR DESCRIPTION
**Pull request by lesserwhirls**
If on mac osx, use system default look and feel. This enables mac key bindings for copy paste. Fixes Unidata/thredds#163

If on a mac, make sure windows are closed when using quit from the system menu. This will trigger the exit method so that the preferences are written out just like if toolsUI was quit using the window 'x' button. [TDS-671]

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Before merging this, can someone test if the gui layout and prefs are saved between sessions of toolsUI on Linux and Windows?

**Comment by msdsoftware** [comment]
Works as desired on the Mac and Windows set-ups I tried. Only thing I didn't like was that the L&F looked odd on Windows until I used the menu item to change it.

BTW: With the shutdown hook connected to the Quit item in the OS X app menu, you could omit the redundant "Exit" menu item in ToolsUI's "System" menu if OS X is detected.

**Comment by cwardgar** [comment]
I resized the ToolsUI window and moved it into the corner. Then I quit and relaunched. The window appeared with the same location and size that it had prior to quitting. So, it looks like prefs are being saved and loaded okay.

@msdsoftware On Windows, toolsUI uses the Nimbus L&F, which looks like [this](http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/ToolsUI/ToolsUI.html). Is that what you got? In that case, that's the intended behavior.

**Comment by msdsoftware** [comment]
I was using Win 7 via Parallels on OS X. The look of the window looked slightly Mac-like, esp. the scroll bars. Maybe that's what Nimbus is supposed to look like, but it didn't match the Win 7 system look.

What I normally do is check the os.name and if it's either OS X or Windows, to set the L&F to
UIManager.setLookAndFeel (UIManager.getSystemLookAndFeelClassName ( ));

Of course, on OS X you'll still get the system L&F without doing this.

**Pull request merged**
