### PR TITLE
Update WMO Grib2 Tables

### PR DESCRIPTION
**Pull request by lesserwhirls**

### CODE REVIEW

**Comment by cwardgar** [comment]
Looks good. Waiting on a rebase.

**Comment by cwardgar** [comment]
I see an "Update branch" button that wasn't there before, but I don't know if I should click it.

**Comment by lesserwhirls** [comment]
I think we can update branch and then, once things pass, we can use the dropdown option on the "Merge pull request" to tell github to rebase.

**Comment by lesserwhirls** [comment]
Looks like that worked? I don't see the merge commit from using the update branch button on github.

**Comment by cwardgar** [comment]
Okay, I did a "Rebase and Merge" this time. As expected, there was no merge commit. That means we don't get the "Merge pull request #683" messages in our commit log. Not sure if I like that any better.

**Comment by lesserwhirls** [comment]
I don't mind pushing an updated branch when one goes stale.

**Pull request merged**
