### PR TITLE
bump ncWMS lib

### PR DESCRIPTION
**Pull request by lesserwhirls**
picks up Unidata/ncWMS#24

### CODE REVIEW

**Comment by cwardgar** [comment]
Do you need this now or can it wait until the next release?

**Comment by lesserwhirls** [comment]
Yeah, I was going to go ahead and do this now...I forgot to deploy the ncWMS snapshot, though. Oops. I'll do that real quick.

**Comment by lesserwhirls** [comment]
Wait, you  mean a new release "now" instead of later? This can wait until the next release - no need to cut `4.6.11`.

**Comment by cwardgar** [comment]
No, I was just asking if you wanted to handle the version increment as part of the next release (it's steps 1 and 6 of [release.md](https://github.com/Unidata/thredds/blob/master/docs/internal/release.md).

But if you need something in `uk.ac.rdg.resc:ncwms:1.2.tds.4.6.11-SNAPSHOT` for development, it makes sense to increment now. Not a big deal either way; the PR's merged.

**Comment by lesserwhirls** [comment]
Ah. Well, good news is that in 5.0, we won't have to worry about most of this. Also, for 5.1, I want to nail down the plugin infrastructure and documentation such that these plugin versions can live on their own, independent of the TDS version.

**Pull request merged**
