### PR TITLE
Unneeded longitude normalization in GribGds.LatLon  (fixes #340) and TDM authentication problem (fixes #361)

### LINKED ISSUE #340: Out of range Lon normalized incorrectly for grib file.
Outputting the stats of the file in question with wgrib I get the following:

```
rec 1:0:date 2015120900 TMPA kpds5=25 kpds6=105 kpds7=2 levels=(0,2) grid=211 2 m above gnd valid 30-30d: bitmap: 55047 undef
  TMPA=Temp. anomaly [K]
  timerange 2 P1 30 P2 30 TimeU 2  nx 360 ny 179 GDS grid 0 num_in_ave 0 missing 0
  center 250 subcenter 1 process 255 Table 2 scan: WE:SN winds(grid) 
  latlon: lat  -89.001000 to 88.998000 by 0.000000  nxny 64440
          long -180.000000 to 179.000000 by 0.000000, (360 x 179) scan 64 mode 8 bdsgrid 1
  min/max data -0.7 3.7  num bits 6  BDS_Ref -7  DecScale 1 BinScale 0
```

but when I read in the same file via GridDataset (`GridDataset gridDataset = GridDataset.open(filename);`) the lon range is wrong.

```
lat -> min: -89.00100708007812 max: 88.99800872802734
lon -> min: 179.99998474121094 max: 539.0
```

I tracked the issue down to [this](https://github.com/Unidata/thredds/blob/5612f5ff64823b8bd36513887236df48748c4290/cdm/src/main/java/ucar/unidata/geoloc/LatLonPointImpl.java#L121)

```
  static public double lonNormal(double lon) {
    if ((lon < -180.) || (lon > 180.)) {
      return Math.IEEEremainder(lon, 360.0);
    } else {
      return lon;
    }
  }
```

Which normalizes the value `-180.00001525878906` to the positive value of  `179.99998474121094`.

I just naively updated the `lonNormal` function to:

```
static public double lonNormal(double lon) {
    if (lon < -180.) {
      return -180.;
    } else if (lon > 180.) {
      return 180.;
    } else {
      return lon;
    }
  }
```

Which is similar to what `latNormal` does, but this breaks a number of tests.  So I think I may be fixing this in the wrong place.

### LINKED ISSUE #361: Fix TDM authentication problem
TDM 4.6 doesn't properly authenticate over SSL.

### PR DESCRIPTION
**Pull request by JohnLCaron**
Both Grib1Gds.LatLon and Grib2Gds.LatLon
makeHorizCoordSys() changed. (rest is reformating)

GitHub Issue 340

need to see if any unit tests are affected.

### CODE REVIEW

**Comment by cwardgar** [comment]
Looks like artifacts.unidata.ucar.edu is back up, so the Gradle build should succeed. This needs to be rebased first though.

**Comment by JohnLCaron** [comment]
OK Ive merged.
Note that this _may_ break some jenkins unit tests. Can revert if interferes with release.

**Comment by cwardgar** [comment]
Okay, I've kicked off a Jenkins build against your master branch: https://jenkins-aws.unidata.ucar.edu/job/cwardgar/15/

May as well fix any broken unit tests before we merge this in.

**Comment by JohnLCaron** [comment]
Not able to replicate test failure locally:

https://jenkins-aws.unidata.ucar.edu/job/threddsMaster/221/testReport/thredds.server.ncss.controller.grid/GridAsPointDataTest/shouldGetData_3_/

**Comment by cwardgar** [comment]
That test uses a `Random` for test input.

**Comment by JohnLCaron** [comment]
1. It looks like NcssRequestUtils and all tests associated with it, including this one, have been removed in 5.0.

2. If we want to keep this test, need to add printouts to identify exact URL so can reproduce.

**Comment by cwardgar** [comment]
It looks like `TestGridAsPointMisc` on 5.0.0 does the same thing as `GridAsPointDataTest, but better (i.e. it's more than just a smoke test and it doesn't use `Random`). So I'm fine with leaving it out of 5.0 and ignoring its random failures on 4.6.

**Comment by cwardgar** [comment]
The results are in on the Jenkins build: https://jenkins-aws.unidata.ucar.edu/job/cwardgar/15/

A lot of failures due to unavailable resources on thredds-test, yay. Do any of those failures look like they're related to the GribGds.LatLon change, or can you not tell?

**Comment by cwardgar** [comment]
Also, it looks like your fix for #361 is now also part of this PR. Is that ready to be merged in? If so, I'll edit the title to note it.

**Comment by JohnLCaron** [comment]
yes, that one can be included (sean tested).

something wrong with thredds-test, unrelated to my changes.
best if we could fix and rerun jenkins

**Comment by lesserwhirls** [comment]
I'm on lead right now...let me see what I can do.

**Comment by cwardgar** [comment]
Okay, it looks like the TDM is re-indexing thredds-test. I'll give it some time and run another Jenkins build against this branch tonight.

**Comment by cwardgar** [comment]
Down to 4 failures, and I very much doubt that they have anything to do with GribGds.LatLon. So, merging this in.

**Comment by JohnLCaron** [comment]
failures seems to be from

2016-02-04T09:57:35.984 -0700 [1112939215][    7362] INFO  -
threddsServlet - Remote host: 184.99.225.242 - Request: "GET
/thredds/catalog/grib/NCEP/RAP/CONUS_40km/files/latest.xml; HTTP/1.1"
2016-02-04T09:57:35.993 -0700 [1112939224][    7362] ERROR -
thredds.server.catalogservice.LocalCatalogServiceController -
handleRequestInternal(): Trouble writing to response.
java.io.FileNotFoundException: Grib Collection 'RAP-CONUS_40km' does
not exist or is empty
	at thredds.catalog.InvDatasetFcGrib.makeDatasetFromCollection(InvDatasetFcGrib.java:178)
~[tdcommon-4.6.4-SNAPSHOT.jar:4.6.4-SNAPSHOT]
	at thredds.catalog.InvDatasetFcGrib.makeDatasetTop(InvDatasetFcGrib.java:486)
~[tdcommon-4.6.4-SNAPSHOT.jar:4.6.4-SNAPSHOT]

**Pull request merged**
