### PR TITLE
setEarthlocation api change

### PR DESCRIPTION
**Pull request by yuanho**
allow location variable to be an array

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Hi @yuanho - do you have a test file that used to cause this to fail?

**Comment by yuanho** [comment]
Yes, where do you want me to upload it?


Yuan

**Comment by lesserwhirls** [comment]
@yuanho - you can probably attach it to this issue if you zip the file.

**Comment by yuanho** [comment]
too big to attach.

Yuan

**Comment by lesserwhirls** [comment]
Dang. Ok, how about RAMADDA or Google Drive?

**Comment by lesserwhirls** [comment]
Ok, I got the file and it's part of our test data now. I am writing some tests for this, and I have a question. The `.isStationary()` method of `CFnetCDF2Dataset` is returning `false` for the example dataset, but the values of `latitude`, `longitude`, and `altitude` arrays each include the same, repeated value...I assume those variables the `latitude`, `longitude`, and `altitude` of the radar? If so, why would `.isStationary()` be `false` if the values of the radar location do not actually change?

Other than `isStationary()`, the only other check is that the dataset can opened as a `Radial` `FeatureType`, which previously it could not.

**Comment by lesserwhirls** [comment]
Hi @yuanho - I'd be happy to help out here, but I'm not sure of the expected behavior. Just let me know if you have any questions!

**Comment by lesserwhirls** [comment]
Hi @yuanho - I think I've at least captured the previous behavior. Let me know if you think this looks ok and we can go ahead and merge it in.

**Comment by lesserwhirls** [comment]
Also, @yuanho, you'll need to "sign" the CLA before we can merge (simple point and click kind of web form). Thanks!

**Comment by lesserwhirls** [comment]
https://artifacts.unidata.ucar.edu/repository/unidata-snapshots/edu/ucar/ncIdv/4.6.12-SNAPSHOT/ncIdv-4.6.12-20180223.180656-18.jar

**Pull request merged**
