### PR TITLE
fix issue #638

### PR DESCRIPTION
**Pull request by JohnLCaron**

### CODE REVIEW

**Comment by msdsoftware** [comment]
Noting that this was performed on the 5.0.0 branch.

Any chance the like can be done on the master branch also, or is that too much a hairball?

**Comment by lesserwhirls** [comment]
I think this can be done on 4.6. Let me make a PR real quick.

**Comment by lesserwhirls** [comment]
Ok, it seemed pretty simple. PR Unidata/thredds#643

**Comment by lesserwhirls** [comment]
@JohnLCaron - thank you so much for this PR!

**Comment by msdsoftware** [comment]
This seems to have worked. Building a netcdfAll SNAPSHOT and using that in Panoply, I can now read the problem data array. Not yet able to plot it correctly yet, but I think that's a separate issue involving the valid_range attribute. Thx.

**Pull request merged**
