### PR TITLE
Upgraded log4j and slf4j to latest version

### PR DESCRIPTION
**Pull request by lesserwhirls**
Fixes odd errors encountered on motherlode

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Thanks @cwardgar!

**Comment by cwardgar** [comment]
Sure. I'm gonna see if I can get Codecov working as well. We've been using [Coveralls](https://coveralls.io/github/Unidata/thredds), but it gets stuck showing spurious builds for some reason.

**Comment by dopplershift** [comment]
💯  to codecov. Had few problems with it for the Python stuff--and only when doing some advanced filtering.

**Comment by cwardgar** [comment]
My concern is that if we upload the coverage at the end of a Travis run (which seems to be what Codecov and the GitHub PR integration expect), it'll only show partial coverage, since not all of our tests run on Travis. We could do it on Jenkins, of course, but I don't think we'll get the feedback in our PRs.

**Comment by dopplershift** [comment]
Not sure how that's a codecov-specific problem...

**Comment by cwardgar** [comment]
It's not really. We'll just have to disable the codecov bot.

**Comment by dopplershift** [comment]
Add a `codecov.yml` file to the repo with:
```yml
comment: off
```

**Pull request merged**
