### PR TITLE
Add test for writing variable with multiple unlimited dims

### PR DESCRIPTION
**Pull request by cwardgar**
* Inspired by https://github.com/Unidata/thredds/issues/581. Turns out we didn't have a good test of this feature yet.

### CODE REVIEW

**Comment by cwardgar** [comment]
I've determined that this test fails on netcdf-4.3.3.1 (what Travis is using) but succeeds on netcdf-4.4.1, which explains why I didn't catch it while testing locally. I'll update this PR to include new netcdf binaries for Travis.

**Comment by cwardgar** [comment]
`TestNc4IospWriting.expandUnlimitedDimensions()` currently [fails on Jenkins](https://jenkins-aws.unidata.ucar.edu/job/cwardgar/24/testReport/junit/ucar.nc2.jni.netcdf/TestNc4IospWriting/expandUnlimitedDimensions/) because it requires netcdf-c 4.4.0+ and we've got an older version on there.

@dopplershift I logged into jenkins-aws but could find no trace of libnetcdf (test output claimed that it was in `/opt/netcdf/lib`). I assume that the shared library is in the snapshot, along with cdmUnitTest/?

**Comment by lesserwhirls** [comment]
Next! Almost there!

**Comment by cwardgar** [comment]
Rebased. Now we're cooking. I'll see if I can upgrade libnetcdf on Jenkins tonight so that the test will pass there as well.

**Comment by lesserwhirls** [comment]
w00t!

**Pull request merged**
