### PR TITLE
Add new link for the FMRC poster

### PR DESCRIPTION
**Pull request by lesserwhirls**

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Very useful .pdf file for the docs. It went missing when John's home directory was archived.

**Comment by lesserwhirls** [comment]
Need to update just a few more links...opps

**Comment by lesserwhirls** [comment]
Ok, that's got it. Should be good to go.

**Comment by cwardgar** [comment]
@lesserwhirls Oops, meant to "Rebase and Merge" this, not "Create a merge commit". Is there a way that you can make the former the default, while still leaving the latter enabled?

**Comment by lesserwhirls** [comment]
It does not look like it. I disabled "Create a merge commit" for now, and will enable it as needed...hopefully not often *laughs*

**Pull request merged**
