### PR TITLE
merge with master

### PR DESCRIPTION
**Pull request by JohnLCaron**

### CODE REVIEW

**Comment by cwardgar** [comment]
There's a failure in Travis:
````
ucar.nc2.util.cache.ReacquireClosedDatasetSpec > reacquire FAILED
    groovy.lang.MissingPropertyException: No such property: location for class: ucar.nc2.util.cache.ReacquireClosedDatasetSpec
        at ucar.nc2.util.cache.ReacquireClosedDatasetSpec.reacquire_closure1(ReacquireClosedDatasetSpec.groovy:26)
        at groovy.lang.Closure.call(Closure.java:426)
        at groovy.lang.Closure.call(Closure.java:442)
        at ucar.nc2.util.cache.ReacquireClosedDatasetSpec.reacquire(ReacquireClosedDatasetSpec.groovy:25)
````

This is because the version of the class [in your merge commit](https://github.com/JohnLCaron/thredds/blob/5.0.0/cdm/src/test/groovy/ucar/nc2/util/cache/ReacquireClosedDatasetSpec.groovy#L26) differs from the version [on master](https://github.com/Unidata/thredds/blob/master/cdm/src/test/groovy/ucar/nc2/util/cache/ReacquireClosedDatasetSpec.groovy#L25). I suspect a mistake during merge conflict resolution.

Anyway, if you think the rest of the merge is correct, you can go ahead and add another small commit that fixes that line in `ReacquireClosedDatasetSpec`. Then I'll merge this PR.

**Comment by cwardgar** [comment]
Scratch that; I fixed `ReacquireClosedDatasetSpec` in [this commit on Unidata:5.0.0](https://github.com/Unidata/thredds/commit/4aaaccbdfad07d54941c87afdc8046d48b8da6c0). JohnLCaron:5.0.0 is out-of-date and so doesn't have it.

@dopplershift Can John simply rebase JohnLCaron:5.0.0 onto the latest Unidata:5.0.0 and magically fix this PR?

**Comment by cwardgar** [comment]
Nevermind, it was a merge conflict after all. I made independent changes to that class on both master and 5.0.0, so it would have been very difficult to resolve that properly without me in the room. I went ahead and merged this and created another PR that fixes the problem: #408.

**Comment by JohnLCaron** [comment]
Thanks. The merge was quite difficult. Im hoping the bulk of our work
switches to 5.0 now.

**Pull request merged**
