### PR TITLE
Fix PointIteratorFilteredSpec."space and time filter"() test

### PR DESCRIPTION
**Pull request by cwardgar**
Will this get us to green on Travis? Hold on to your butts...

### CODE REVIEW

**Comment by dopplershift** [comment]
Looks like it broke a different test?

**Comment by cwardgar** [comment]
Nope, afraid not. We still have:
````
ucar.nc2.ft.point.writer.TestCFPointWriterMisc > testAltUnits FAILED
    java.lang.AssertionError
        at ucar.nc2.ft.point.writer.TestCFPointWriterMisc.rewriteDataset(TestCFPointWriterMisc.java:266)
        at ucar.nc2.ft.point.writer.TestCFPointWriterMisc.testAltUnits(TestCFPointWriterMisc.java:158)
````
This PR is still good though.

**Comment by cwardgar** [comment]
@dopplershift I believe that the Gradle test executor aborts as soon as any subproject has a test failure. So what probably happened is that `ucar.nc2.ft.point.writer.TestCFPointWriterMisc.testAltUnits` (which lives in `cdm-test`) has been broken for a while, but it was hidden by the earlier failure of this test in `cdm`.

**Comment by dopplershift** [comment]
Alright. Fixing the next one can be another PR.

**Pull request merged**
