### PR TITLE
Build failed when executing gradle 2.13 (latest release)

### PR DESCRIPTION
**Pull request by vegasm**
Incremented version of the gradle shadow plugin to 1.2.3, which contains a fix for compability with gradle 2.11 and higher

### CODE REVIEW

**Comment by cwardgar** [comment]
I'm curious: why aren't you using the [wrapper](https://github.com/Unidata/thredds/blob/5.0.0/gradlew) to build? It's meant to prevent precisely these kind of build failures, where developers are using different system-installed versions of Gradle.

**Comment by vegasm** [comment]
I was not able to import the project in IntelliJ using the latest gradle version. After fixing that, everything worked fine. Is there any option to use the wrapper in Intellij? I was using eclipse and it is new for me.

**Comment by cwardgar** [comment]
Yes, there's a way to use the wrapper in IntelliJ: 
screen shot 2016-05-09 at 3 13 03 pm

I don't know for sure about Eclipse, but I'd be surprised if it weren't possible there as well.

**Comment by cwardgar** [comment]
This is a non-issue when using the wrapper, so I'm going to go ahead and close it. The shadow plugin version will get incremented when we update to a newer Gradle. I think I've already done that in a branch, actually.

**Pull request closed without merging**
