### PR TITLE
Proto version

### PR DESCRIPTION
**Pull request by JohnLCaron**
upgrade protobuf to 3.6.1
regenerate grib protos by hand.

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Will this require a regeneration of .ncx files for those running a 5.0 beta?

**Comment by JohnLCaron** [comment]
Thats a good question, let me make sure that the answer is no.

**Comment by JohnLCaron** [comment]
So this problem affects both grib1Index.proto / Grib1Index.java and grib2Index.proto / Grib2Index.java.

10/16/15 we upgraded protos to proto3.
11/28/15 we added proto_version field so we could deal with any changes between proto2 and proto3.
12/1/15 we reverted to use proto2 and changed the name to version (not proto_version).

Issue #306 captures the thought processes for all that.

This PR was just intended to upgrade the protobuf library. However, when I forced recompiled the protos with the new version of protoc, I got a compile error indicating the GibXIndex.java was still referencing proto_version field. That could only work if the protos checked in on 12/1/15 had never been recompiled.

We could probably assume that no one else recompiled them, else it would have failed and likely they would have reported it. But who knows if there are versions out there with a version field but not a proto_version field. Since they both use field number #4, the binary form is compatible.

The field isnt actually needed, nor used anywhere. So Im going to remove it from the code. Ill reserve that field in the proto so we never use it. If we decide we need something, we can just create a new field with a new field number.

Note that this implies protos are not being recompiled as part of the build process. We might want to look at that harder.

Current best practice is to never use "required" modifier. If we had done that, we could upgrade to proto3 with ease. We can revisit proto3 upgrades another time.

**Comment by lesserwhirls** [comment]
Ok, just finished the Jenkins run and this fixes four more tests - that take us back to where we were with 8 failing tests. Once this is rebased, I'll merge it in.

**Pull request merged**
