### PR TITLE
Upgrade a few dependencies

### PR DESCRIPTION
**Pull request by lesserwhirls**
migrate to Thymeleaf 3.x

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Running on Jenkins, too. Let's hold off until we see how that run goes.

**Comment by cwardgar** [comment]
Can you add some comments that explain which old versions you're overriding and which first level dependencies are dragging them in?

**Comment by lesserwhirls** [comment]
Ok, this one is updated.

**Comment by cwardgar** [comment]
Reorganized a bit. Travis doesn't want to run right now though.

**Pull request merged**
