### PR TITLE
Remove special case code from CoordSysBuilder

### PR DESCRIPTION
**Pull request by lesserwhirls**
Fixes Unidata/thredds#766

### CODE REVIEW

**Comment by lesserwhirls** [comment]
If this passes Travis, let's do a Jenkins run on this to see if anything breaks.

**Comment by cwardgar** [comment]
Looks good so far. I'll wait for Jenkins before I merge.

**Comment by lesserwhirls** [comment]
fingers crossed 🤞 

https://jenkins-aws.unidata.ucar.edu/job/sarms/8/

**Comment by lesserwhirls** [comment]
Looks like I ran 4.6.x pointing to 5.0 grib index files?

I made a copy of `threddsMaster`, which seems to do the right thing, and am re-running based on my branch.

**Comment by cwardgar** [comment]
I think I know what's going on here. I recently `rsync`ed my local `cdmUnitTest` directory to Jenkins, so that it would have `UpperDeschutes_t4p10_swemelt.nc` and any other file it was missing. A lot of 5.0-only index files got copied over as well. I noticed that at the time, and made sure to nuke all `.gbx9`, `.ncx3`, and `.ncx4` files. That resulted in [this](https://jenkins-aws.unidata.ucar.edu/job/thredds5.0/276/testReport/).

So, I copied the indexes back over and got [this](https://jenkins-aws.unidata.ucar.edu/job/thredds5.0/277/testReport/). Fixed! But only for 5.0, it seems.

I'm not sure what to do here. Clearly our 5.0 tests expect _some_ indexes to exist, but many of those aren't compatible with 4.6. Ideally, `cdmUnitTest/` wouldn't contain any index files whatsoever and they'd all be recreated during testing, but I don't know how far away we are from that goal.

**Comment by lesserwhirls** [comment]
Looks like I need to get a local copy of the test data. I wonder how it is that `threddsMaster` ran successfully (minus the dap tests) on Jenkins on the 22 of Feb? @dopplershift - do you recall anything about the 4.6 vs 5.0 grib indexes on Jenkins?

**Comment by lesserwhirls** [comment]
I am going to get a local copy of the test data and run things, but it looks like those lines are not even touched by our current testing suite:

https://jenkins-aws.unidata.ucar.edu/job/threddsMaster/285/jacoco/ucar.nc2.dataset/CoordSysBuilder/

(look around line 1221).

**Comment by cwardgar** [comment]
I think that's right. According to IntelliJ, the private `VarProcess` ctor is only used by one method, and that method isn't used anywhere else. So maybe you can nuke all of it? That'd be great.

**Comment by lesserwhirls** [comment]
Comparing the test results on Jenkins for [this PR](https://jenkins-aws.unidata.ucar.edu/job/sarms.4.6.x/lastCompletedBuild/testReport/) vs [master](https://jenkins-aws.unidata.ucar.edu/job/threddsMaster/lastBuild/testReport/) shows no new failing tests. I think we are good to go.

**Comment by cwardgar** [comment]
There seems to be a lot more code in `CoordSysBuilder` that's unused. Do you want to try to nuke all of that now too?

**Comment by lesserwhirls** [comment]
I'd feel better about nuking that stuff in a PR for 5.0. Do you think that would be ok?

**Comment by cwardgar** [comment]
Yeah, that makes sense.

**Pull request merged**
