### PR TITLE
Release 4.6.4; begin work on 4.6.5-SNAPSHOT

### PR DESCRIPTION
**Pull request by cwardgar**

### CODE REVIEW

**Comment by cwardgar** [comment]
I need to create a tag for the release (I have it on [my repo](https://github.com/cwardgar/thredds/tree/v4.6.4), but tags don't get included in pull requests. I'm blocked until I merge this in.

**Comment by cwardgar** [comment]
For me, the command was
````
git push --tags --repo=Unidata
````
to push the `v4.6.4` tag I had on cwardgar/thredds (and which I track on my local machine) to Unidata/thredds. I'll update release.txt.

**Comment by dopplershift** [comment]
I knew about `--tags`. I'm curious why `--repo` was necessary.

**Comment by cwardgar** [comment]
Because my local repo is tracking cwardgar/thredds, not Unidata/thredds

**Comment by dopplershift** [comment]
Your repo isn't tracking anything...only branches do. Then again, I'm not sure how it would resolve the ambiguity of where tags should go otherwise.

**Pull request merged**
