### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by lesserwhirls**
Update:
* `spring`
* `spring-security`
* `edal-java`
* `chronicle-map`

The last two (`edal-java` and `chronicle-map`) allow us to stop forcing versions of two transitive dependencies (`xtream` and `commons-collections`).

### CODE REVIEW

**Comment by cwardgar** [comment]
Looks good. I just added a commit that clarified (mostly to myself) how the transitive dependency analysis is being done. I also double-checked that none of the rules you nuked relate to deps that are still being used by the project.

**Comment by lesserwhirls** [comment]
Good call - double checking is never a bad thing. Adding the gradle command used to check the transitive dependencies is also a good thing (I have to google every time). I have also seen a little gradle snippet for doing a `dependencyInsight` check on all modules in one command, in case you don't know where the transitive dependency might live. For [example](https://solidsoft.wordpress.com/2014/11/19/gradle-tricks-tracking-down-not-expected-transitive-dependencies/) - maybe we should add our own `allDepInsight`?

**Comment by cwardgar** [comment]
I tried it out, but it generates an awful lot of noise:
```
./gradlew allDepInsight --configuration runtime --dependency commons-logging
:buildSrc:compileJava NO-SOURCE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:pluginDescriptors UP-TO-DATE
:buildSrc:processResources NO-SOURCE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:pluginUnderTestMetadata UP-TO-DATE
:buildSrc:compileTestJava NO-SOURCE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:validateTaskProperties UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
:bufr:allDepInsight
commons-logging:commons-logging:1.2
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- project :httpservices
     |    \--- project :cdm
     |         \--- runtime
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- project :httpservices (*)

(*) - dependencies omitted (listed previously)
:cdm:allDepInsight
commons-logging:commons-logging:1.2
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- project :httpservices
     |    \--- runtime
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- project :httpservices (*)

(*) - dependencies omitted (listed previously)
:cdm-test:allDepInsight
No dependencies matching given input were found in configuration ':cdm-test:runtime'
:clcommon:allDepInsight
commons-logging:commons-logging:1.2
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- project :httpservices
     |    \--- project :cdm
     |         \--- runtime
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- project :httpservices (*)

(*) - dependencies omitted (listed previously)
:grib:allDepInsight
commons-logging:commons-logging:1.2
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- project :httpservices
     |    \--- project :cdm
     |         \--- runtime
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- project :httpservices (*)

(*) - dependencies omitted (listed previously)
:httpservices:allDepInsight
commons-logging:commons-logging:1.2
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- runtime
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- runtime

(*) - dependencies omitted (listed previously)
:it:allDepInsight
No dependencies matching given input were found in configuration ':it:runtime'
:legacy:allDepInsight
commons-logging:commons-logging:1.2 (conflict resolution)
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- project :opendap
     |    \--- runtime
     +--- project :httpservices
     |    +--- project :cdm
     |    |    +--- runtime
     |    |    \--- project :opendap (*)
     |    \--- project :opendap (*)
     +--- com.amazonaws:aws-java-sdk-core:1.11.113
     |    +--- com.amazonaws:aws-java-sdk-s3:1.11.113
     |    |    \--- runtime
     |    \--- com.amazonaws:aws-java-sdk-kms:1.11.113
     |         \--- com.amazonaws:aws-java-sdk-s3:1.11.113 (*)
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- project :httpservices (*)

commons-logging:commons-logging:1.1.3 -> 1.2
\--- com.amazonaws:aws-java-sdk-core:1.11.113
     +--- com.amazonaws:aws-java-sdk-s3:1.11.113
     |    \--- runtime
     \--- com.amazonaws:aws-java-sdk-kms:1.11.113
          \--- com.amazonaws:aws-java-sdk-s3:1.11.113 (*)

(*) - dependencies omitted (listed previously)
:netcdf4:allDepInsight
commons-logging:commons-logging:1.2
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- project :httpservices
     |    \--- project :cdm
     |         \--- runtime
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- project :httpservices (*)

(*) - dependencies omitted (listed previously)
:opendap:allDepInsight
commons-logging:commons-logging:1.2
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- runtime
     +--- project :httpservices
     |    +--- runtime
     |    \--- project :cdm
     |         \--- runtime
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- project :httpservices (*)

(*) - dependencies omitted (listed previously)
:tdcommon:allDepInsight
commons-logging:commons-logging:1.2
+--- org.apache.httpcomponents:httpclient:4.5.2
|    +--- project :httpservices
|    |    \--- project :cdm
|    |         +--- runtime
|    |         \--- project :grib
|    |              \--- runtime
|    \--- org.apache.httpcomponents:httpmime:4.5.2
|         \--- project :httpservices (*)
\--- org.springframework:spring-core:4.3.8.RELEASE
     +--- runtime
     +--- org.springframework:spring-context:4.3.8.RELEASE
     |    \--- runtime
     +--- org.springframework:spring-beans:4.3.8.RELEASE
     |    +--- runtime
     |    +--- org.springframework:spring-context:4.3.8.RELEASE (*)
     |    \--- org.springframework:spring-aop:4.3.8.RELEASE
     |         \--- org.springframework:spring-context:4.3.8.RELEASE (*)
     +--- org.springframework:spring-aop:4.3.8.RELEASE (*)
     \--- org.springframework:spring-expression:4.3.8.RELEASE
          \--- org.springframework:spring-context:4.3.8.RELEASE (*)

(*) - dependencies omitted (listed previously)
:tdm:allDepInsight
commons-logging:commons-logging:1.2
+--- org.apache.httpcomponents:httpclient:4.5.2
|    +--- runtime
|    +--- project :httpservices
|    |    +--- runtime
|    |    \--- project :cdm
|    |         +--- runtime
|    |         +--- project :grib
|    |         |    +--- runtime
|    |         |    \--- project :tdcommon
|    |         |         \--- runtime
|    |         \--- project :tdcommon (*)
|    \--- org.apache.httpcomponents:httpmime:4.5.2
|         \--- project :httpservices (*)
\--- org.springframework:spring-core:4.3.8.RELEASE
     +--- runtime
     +--- project :tdcommon (*)
     +--- org.springframework:spring-context:4.3.8.RELEASE
     |    +--- runtime
     |    \--- project :tdcommon (*)
     +--- org.springframework:spring-beans:4.3.8.RELEASE
     |    +--- project :tdcommon (*)
     |    +--- org.springframework:spring-context:4.3.8.RELEASE (*)
     |    \--- org.springframework:spring-aop:4.3.8.RELEASE
     |         \--- org.springframework:spring-context:4.3.8.RELEASE (*)
     +--- org.springframework:spring-aop:4.3.8.RELEASE (*)
     \--- org.springframework:spring-expression:4.3.8.RELEASE
          \--- org.springframework:spring-context:4.3.8.RELEASE (*)

(*) - dependencies omitted (listed previously)
:tds:allDepInsight
commons-logging:commons-logging:1.2
+--- org.apache.httpcomponents:httpclient:4.5.2
|    +--- runtime
|    +--- project :httpservices
|    |    +--- runtime
|    |    +--- project :cdm
|    |    |    +--- runtime
|    |    |    +--- project :bufr
|    |    |    |    \--- runtime
|    |    |    +--- project :clcommon
|    |    |    |    \--- runtime
|    |    |    +--- project :grib
|    |    |    |    +--- runtime
|    |    |    |    +--- project :tdcommon
|    |    |    |    |    \--- runtime
|    |    |    |    \--- project :visadCdm
|    |    |    |         \--- runtime
|    |    |    +--- project :netcdf4
|    |    |    |    +--- runtime
|    |    |    |    \--- project :dap4:d4cdm
|    |    |    |         \--- runtime
|    |    |    +--- project :opendap
|    |    |    |    \--- runtime
|    |    |    +--- project :tdcommon (*)
|    |    |    +--- project :waterml
|    |    |    |    \--- runtime
|    |    |    +--- project :dap4:d4cdm (*)
|    |    |    \--- project :visadCdm (*)
|    |    +--- project :opendap (*)
|    |    +--- project :dap4:d4servlet
|    |    |    \--- runtime
|    |    \--- project :dap4:d4lib
|    |         +--- runtime
|    |         +--- project :dap4:d4cdm (*)
|    |         \--- project :dap4:d4servlet (*)
|    +--- project :opendap (*)
|    +--- project :dap4:d4lib (*)
|    \--- org.apache.httpcomponents:httpmime:4.5.2
|         \--- project :httpservices (*)
\--- org.springframework:spring-core:4.3.8.RELEASE
     +--- runtime
     +--- project :tdcommon (*)
     +--- org.springframework:spring-context:4.3.8.RELEASE
     |    +--- runtime
     |    +--- project :tdcommon (*)
     |    +--- org.springframework:spring-web:4.3.8.RELEASE
     |    |    +--- runtime
     |    |    +--- org.springframework:spring-webmvc:4.3.8.RELEASE
     |    |    |    +--- runtime
     |    |    |    \--- EDS:threddsIso:2.3.0-SNAPSHOT
     |    |    |         \--- runtime
     |    |    \--- org.springframework.security:spring-security-web:4.2.2.RELEASE
     |    |         \--- runtime
     |    +--- org.springframework:spring-webmvc:4.3.8.RELEASE (*)
     |    +--- org.springframework.security:spring-security-web:4.2.2.RELEASE (*)
     |    +--- org.springframework.security:spring-security-config:4.2.2.RELEASE
     |    |    \--- runtime
     |    \--- org.springframework.security:spring-security-core:4.2.2.RELEASE
     |         +--- org.springframework.security:spring-security-web:4.2.2.RELEASE (*)
     |         \--- org.springframework.security:spring-security-config:4.2.2.RELEASE (*)
     +--- org.springframework:spring-beans:4.3.8.RELEASE
     |    +--- runtime
     |    +--- project :tdcommon (*)
     |    +--- org.springframework:spring-context:4.3.8.RELEASE (*)
     |    +--- org.springframework:spring-web:4.3.8.RELEASE (*)
     |    +--- org.springframework:spring-webmvc:4.3.8.RELEASE (*)
     |    +--- org.springframework.security:spring-security-web:4.2.2.RELEASE (*)
     |    +--- org.springframework.security:spring-security-config:4.2.2.RELEASE (*)
     |    +--- org.springframework:spring-aop:4.3.8.RELEASE
     |    |    +--- org.springframework:spring-context:4.3.8.RELEASE (*)
     |    |    +--- org.springframework:spring-web:4.3.8.RELEASE (*)
     |    |    +--- org.springframework:spring-webmvc:4.3.8.RELEASE (*)
     |    |    +--- org.springframework.security:spring-security-config:4.2.2.RELEASE (*)
     |    |    \--- org.springframework.security:spring-security-core:4.2.2.RELEASE (*)
     |    \--- org.springframework.security:spring-security-core:4.2.2.RELEASE (*)
     +--- org.springframework:spring-web:4.3.8.RELEASE (*)
     +--- org.springframework:spring-webmvc:4.3.8.RELEASE (*)
     +--- org.springframework.security:spring-security-web:4.2.2.RELEASE (*)
     +--- org.springframework.security:spring-security-config:4.2.2.RELEASE (*)
     +--- EDS:threddsIso:2.3.0-SNAPSHOT (*)
     +--- org.springframework:spring-aop:4.3.8.RELEASE (*)
     +--- org.springframework:spring-expression:4.3.8.RELEASE
     |    +--- org.springframework:spring-context:4.3.8.RELEASE (*)
     |    +--- org.springframework:spring-webmvc:4.3.8.RELEASE (*)
     |    +--- org.springframework.security:spring-security-web:4.2.2.RELEASE (*)
     |    \--- org.springframework.security:spring-security-core:4.2.2.RELEASE (*)
     \--- org.springframework.security:spring-security-core:4.2.2.RELEASE (*)

(*) - dependencies omitted (listed previously)
:testUtil:allDepInsight
commons-logging:commons-logging:1.2
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- project :httpservices
     |    +--- runtime
     |    \--- project :cdm
     |         \--- runtime
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- project :httpservices (*)

(*) - dependencies omitted (listed previously)
:udunits:allDepInsight
No dependencies matching given input were found in configuration ':udunits:runtime'
:ui:allDepInsight
commons-logging:commons-logging:1.2
+--- org.apache.httpcomponents:httpclient:4.5.2
|    +--- runtime
|    +--- project :opendap
|    |    \--- runtime
|    +--- project :httpservices
|    |    +--- runtime
|    |    +--- project :cdm
|    |    |    +--- runtime
|    |    |    +--- project :clcommon
|    |    |    |    \--- runtime
|    |    |    +--- project :bufr
|    |    |    |    \--- runtime
|    |    |    +--- project :grib
|    |    |    |    +--- runtime
|    |    |    |    \--- project :visadCdm
|    |    |    |         \--- runtime
|    |    |    +--- project :netcdf4
|    |    |    |    \--- runtime
|    |    |    +--- project :opendap (*)
|    |    |    +--- project :visadCdm (*)
|    |    |    \--- project :waterml
|    |    |         \--- runtime
|    |    \--- project :opendap (*)
|    \--- org.apache.httpcomponents:httpmime:4.5.2
|         \--- project :httpservices (*)
\--- org.springframework:spring-core:4.3.8.RELEASE
     +--- org.springframework:spring-context:4.3.8.RELEASE
     |    \--- runtime
     +--- org.springframework:spring-aop:4.3.8.RELEASE
     |    \--- org.springframework:spring-context:4.3.8.RELEASE (*)
     +--- org.springframework:spring-beans:4.3.8.RELEASE
     |    +--- org.springframework:spring-context:4.3.8.RELEASE (*)
     |    \--- org.springframework:spring-aop:4.3.8.RELEASE (*)
     \--- org.springframework:spring-expression:4.3.8.RELEASE
          \--- org.springframework:spring-context:4.3.8.RELEASE (*)

(*) - dependencies omitted (listed previously)
:visadCdm:allDepInsight
commons-logging:commons-logging:1.2
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- project :httpservices
     |    \--- project :cdm
     |         +--- runtime
     |         \--- project :grib
     |              \--- runtime
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- project :httpservices (*)

(*) - dependencies omitted (listed previously)
:waterml:allDepInsight
commons-logging:commons-logging:1.2
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- project :httpservices
     |    \--- project :cdm
     |         \--- runtime
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- project :httpservices (*)

(*) - dependencies omitted (listed previously)
:dap4:d4cdm:allDepInsight
commons-logging:commons-logging:1.2
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- project :dap4:d4lib
     |    \--- runtime
     +--- project :httpservices
     |    +--- project :dap4:d4lib (*)
     |    \--- project :cdm
     |         +--- runtime
     |         \--- project :netcdf4
     |              \--- runtime
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- project :httpservices (*)

(*) - dependencies omitted (listed previously)
:dap4:d4core:allDepInsight
No dependencies matching given input were found in configuration ':dap4:d4core:runtime'
:dap4:d4lib:allDepInsight
commons-logging:commons-logging:1.2
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- runtime
     +--- project :httpservices
     |    \--- runtime
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- project :httpservices (*)

(*) - dependencies omitted (listed previously)
:dap4:d4servlet:allDepInsight
commons-logging:commons-logging:1.2
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- project :dap4:d4lib
     |    \--- runtime
     +--- project :httpservices
     |    +--- runtime
     |    \--- project :dap4:d4lib (*)
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- project :httpservices (*)

(*) - dependencies omitted (listed previously)
:dap4:d4tests:allDepInsight
commons-logging:commons-logging:1.2
\--- org.springframework:spring-core:4.3.8.RELEASE
     +--- runtime
     +--- org.springframework:spring-test:4.3.8.RELEASE
     |    \--- runtime
     +--- org.springframework:spring-context:4.3.8.RELEASE
     |    +--- runtime
     |    +--- org.springframework:spring-web:4.3.8.RELEASE
     |    |    +--- runtime
     |    |    \--- org.springframework:spring-webmvc:4.3.8.RELEASE
     |    |         \--- runtime
     |    \--- org.springframework:spring-webmvc:4.3.8.RELEASE (*)
     +--- org.springframework:spring-beans:4.3.8.RELEASE
     |    +--- runtime
     |    +--- org.springframework:spring-context:4.3.8.RELEASE (*)
     |    +--- org.springframework:spring-web:4.3.8.RELEASE (*)
     |    +--- org.springframework:spring-webmvc:4.3.8.RELEASE (*)
     |    \--- org.springframework:spring-aop:4.3.8.RELEASE
     |         +--- org.springframework:spring-context:4.3.8.RELEASE (*)
     |         +--- org.springframework:spring-web:4.3.8.RELEASE (*)
     |         \--- org.springframework:spring-webmvc:4.3.8.RELEASE (*)
     +--- org.springframework:spring-web:4.3.8.RELEASE (*)
     +--- org.springframework:spring-webmvc:4.3.8.RELEASE (*)
     +--- org.springframework:spring-aop:4.3.8.RELEASE (*)
     \--- org.springframework:spring-expression:4.3.8.RELEASE
          +--- org.springframework:spring-context:4.3.8.RELEASE (*)
          \--- org.springframework:spring-webmvc:4.3.8.RELEASE (*)

(*) - dependencies omitted (listed previously)
:dap4:d4ts:allDepInsight
commons-logging:commons-logging:1.2
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- project :dap4:d4lib
     |    +--- runtime
     |    \--- project :dap4:d4servlet
     |         \--- runtime
     +--- project :httpservices
     |    +--- project :dap4:d4lib (*)
     |    \--- project :dap4:d4servlet (*)
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- project :httpservices (*)

(*) - dependencies omitted (listed previously)
:opendap:dtswar:allDepInsight
commons-logging:commons-logging:1.2
\--- org.apache.httpcomponents:httpclient:4.5.2
     +--- project :opendap
     |    \--- runtime
     +--- project :httpservices
     |    +--- project :cdm
     |    |    +--- runtime
     |    |    \--- project :opendap (*)
     |    \--- project :opendap (*)
     \--- org.apache.httpcomponents:httpmime:4.5.2
          \--- project :httpservices (*)

(*) - dependencies omitted (listed previously)

BUILD SUCCESSFUL

Total time: 1.136 secs
```
Furthermore, it only searches the `runtime` configuration. What about `testCompile` and others?

A really bullet-proof and non-spammy task is possible, but it would take some work. Do you think we need that? TDS's runtime configuration covers probably 95% of all the dependencies we use.

**Comment by lesserwhirls** [comment]
Nah, it would be something nice to have (like, say, a million dollars would be nice), but it's not super critical or anything. I think we're good without it.

**Comment by lesserwhirls** [comment]
Thanks for checking it out, though!

**Pull request merged**
