### PR TITLE
Grib1Record.readDataRaw() now actually does what it claims

### LINKED ISSUE #758: Grib1Record.readDataRaw() expands Quasi Grid
I am integrating the thredds GRIB API into a legacy application that used a much older version of the library. One of the things that the application does is to expand a GRIB edition 1 thinned grid into a regular grid.  Unfortunately, this action is in conflict with the thredds Grib1Record.readData() method because the API already this action built in.  Rather than modifying the legacy code,  I thought I'd use the Grib1Record.readDataRaw() method which carries the comment "dont convertQuasiGrid".  However, that method is just a pass-through to the readData method.   It was easy enough to hack the code to make it not convert the quasi GRID, but I was wondering if the existing behavior should be viewed as a bug and if it would be changed in future releases.  

The version 4.8.6 code is shown below.  In my hack, I simply copied up the body of readData and removed the quasi-regular conversion.

~~~~
 // dont convertQuasiGrid
  public float[] readDataRaw(RandomAccessFile raf, GribData.InterpolationMethod method) throws IOException {
    return readData(raf, method);
  }

  // isolate dependencies here - in case we have a minimal I/O mode where not all fields are available
  private float[] readData(RandomAccessFile raf, GribData.InterpolationMethod method) throws IOException {
    Grib1Gds gds = getGDS();
    Grib1DataReader reader = new Grib1DataReader(pdss.getDecimalScale(), gds.getScanMode(), gds.getNxRaw(), gds.getNyRaw(), gds.getNpts(), dataSection.getStartingPosition());
    byte[] bm = (bitmap == null) ? null : bitmap.getBitmap(raf);
    float[] data = reader.getData(raf, bm);

    if (gdss.isThin()) {
      data = QuasiRegular.convertQuasiGrid(data, gds.getNptsInLine(), gds.getNxRaw(), gds.getNyRaw(), method);
    }

    lastRecordRead = this;
    return data;
  }
 
~~~~

### PR DESCRIPTION
**Pull request by cwardgar**
* This resolves #758.
* Made `Grib1Record.readData(RandomAccessFile, GribData.InterpolationMethod)` public.
* Two spots where `readDataRaw()` was (confusingly) used now call the newly-available `readData()` instead.

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Looks good. Would you mind running this through Jenkins? I don't think anything will change, but just to be sure no new errors are introduced.

**Comment by cwardgar** [comment]
Sure, it's running at https://jenkins-aws.unidata.ucar.edu/job/thredds5.0/

**Comment by cwardgar** [comment]
Looks good. There's even one less test failure, somehow.

https://jenkins-aws.unidata.ucar.edu/job/thredds5.0/273/testReport/

**Comment by lesserwhirls** [comment]
Hey man, one less failing test...

ship it

**Pull request merged**
