### PR TITLE
Ncwms2

### PR DESCRIPTION
**Pull request by lesserwhirls**
See Unidata/thredds#234 for more info.

### CODE REVIEW

**Comment by cwardgar** [comment]
As you said, there are a ton of binaries in the commit. [This one](https://github.com/lesserwhirls/thredds/blob/ncwms2/tds/src/main/gwt-unitCache/gwt-unitCache-c04dfa348afbdd12c2a9ddc3bc36901a78fa6812-00000151A815CA3B), in particular, is 70 MB. I think we should try hard to keep them out of Git. You said it's a Gradle issue?

**Comment by lesserwhirls** [comment]
Yikes! I didn't see that one.

It's not a gradle issue, per se, but a problem that gradle can fix. There
appear to be ways to have gradle use gwt to compile during the build
process, so none of those binary files would be included in guthub (or
anything in arc/main/webapp/). I can check the gradle stuff out if you are
not interested in it.

**Comment by cwardgar** [comment]
I got some other stuff I want to finish, but I might be able to help if you get stuck.

**Comment by lesserwhirls** [comment]
Hi Christian,

Sounds good - I'm interested in gradle as well, so this should be fun!

Thanks!

Sean

**Comment by lesserwhirls** [comment]
Ok, this gets rid of the large bin files, and adds edal-java wms and godiva3. The next steps are to:

1. Build gwt stuff for godiva3 using gwt
2. Create branch on Unidata/ncWMS for 5.0 which includes the changes from this PR as well as the gradle build
3. Make sure the thredds gradle build knows how to pull out, from the ncwms 5.0 artifact, the things that are needed for the thredds.war file.

Now the question is, do we want to merge this in "as is", or "go for the silver" and make the three requirements above work.

Now ideally, we would "go for the gold" in that the TDS would look, in say, `${content root}/thredds/plugins/services`, investigate what is there, and deploy and enable those services (for example, ncWMS and threddsIso) at runtime.

**Comment by lesserwhirls** [comment]
Not sure what happened with build.gradle - I'll try to clean that up so that the diff isn't the whole file!

**Comment by lesserwhirls** [comment]
Ok, bumped the edal-java deps to the latest release. Not sure I can cleanup the build.gradle diff...no idea what happened there. If this passes, then we are good to go in terms of merging this, unless you all see something I've missed.

**Comment by lesserwhirls** [comment]
So travis failed:

---
thredds.server.ncss.validation.TestNcssParams > classMethod FAILED
    java.lang.NoSuchMethodError: javax.validation.spi.ConfigurationState.getParameterNameProvider()Ljavax/validation/ParameterNameProvider;
        at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:142)
        at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:35)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:302)
        at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:111)
        at thredds.server.ncss.validation.TestNcssParams.setUp(TestNcssParams.java:27)
---

Nothing in this PR should have affected the NCSS stuff. Any thoughts?

**Comment by lesserwhirls** [comment]
My guess is John's PR fixed it, which caused travis to go green. I just merged John's PR and rebased. Let's see how it goes.

**Comment by cwardgar** [comment]
If that fails, my guess would be that the edal stuff is dragging in transitive dependencies that aren't jiving with what TDS currently uses. Specifically:
```groovy
    compile libraries["validation-api"]
    runtime libraries["hibernate-validator"]
```
You can use Gradle's [dependency task](https://docs.gradle.org/current/userguide/tutorial_gradle_command_line.html#sec:listing_dependencies) to investigate.

**Comment by cwardgar** [comment]
And now:
```
ucar.nc2.util.cache.ReacquireClosedDatasetSpec > classMethod FAILED
    java.lang.IllegalStateException: Timer already cancelled.
        at java.util.Timer.sched(Timer.java:397)
        at java.util.Timer.scheduleAtFixedRate(Timer.java:328)
        at ucar.nc2.util.cache.FileCache.<init>(FileCache.java:178)
        at ucar.nc2.dataset.NetcdfDataset.initNetcdfFileCache(NetcdfDataset.java:291)
        at ucar.nc2.util.cache.ReacquireClosedDatasetSpec.setupSpec(ReacquireClosedDatasetSpec.groovy:17)
```
which is one of my tests that John's already pointed out to me. I'll have a look later.

**Comment by lesserwhirls** [comment]
Ok...I'm just glad I got the new godiva stuff building with gradle :-)
Although, it really slows down the build of the tds war. We should
definitely make moving this out of the THREDDS project to the ncwms project
soon.

**Comment by cwardgar** [comment]
I can't reproduce locally, but I suspect a race condition. Yay. Digging some more.

**Comment by rsignell-usgs** [comment]
@cwardgar , I will test the ncWMS2/UGRID capabilities as soon as this is ready.

**Comment by cwardgar** [comment]
Yeah, I'm gonna work on this today; I was on leave both yesterday and Friday.

**Comment by rsignell-usgs** [comment]
@cwardgar , excellent.   Note that UGRID was not working properly prior to this bugfix release:
https://github.com/Reading-eScience-Centre/edal-java/releases/tag/edal-1.1.1
so hopefully you can upgrade your version of ncWMS2 to that one.

**Comment by lesserwhirls** [comment]
Hi @rsignell-usgs - we are using the 1.1.1 release, so we should be good to go:

https://github.com/lesserwhirls/thredds/blob/ncwms2/gradle/dependencies.gradle

Cheers!

Sean

**Comment by rsignell-usgs** [comment]
@lesserwhirls , woo hoo!   Okay, fingers crossed here on Travis passing!   :smile_cat:

**Comment by cwardgar** [comment]
I can't reproduce this at all: not locally, on Travis, or on Jenkins. I imagine that if you rebase this onto the newest 5.0.0, Travis will pass.

I still suspect a race condition, but it's not a problem that will affect us in production. Specifically, `NetcdfDataset.initNetcdfFileCache()` and `NetcdfDataset.shutdown()` were designed assuming that we'd call each exactly once, which we do in production. In our tests, however, we're now calling them multiple times, and I really want to get that working consistently.

So yeah, I expect to see this again, and eventually I'm going to have to figure out the root cause, but I don't see why it should delay this PR.

**Comment by cwardgar** [comment]
So I took a shot at fixing this: #473. Go ahead and merge that one in before this one.

**Comment by cwardgar** [comment]
So we're getting the original failure again:
```
thredds.server.ncss.validation.TestNcssParams > classMethod FAILED
    java.lang.NoSuchMethodError: javax.validation.spi.ConfigurationState.getParameterNameProvider()Ljavax/validation/ParameterNameProvider;
        at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:142)
        at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:35)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:302)
        at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:111)
        at thredds.server.ncss.validation.TestNcssParams.setUp(TestNcssParams.java:27)
```

**Comment by lesserwhirls** [comment]
Ok, there was an older version of `javax.validation:validation-api` being pulled in by `edal-godiva`. Let's give this one a shot.

**Comment by lesserwhirls** [comment]
ok, one more old copy coming in from the gwt plugin...come on, travis!

**Comment by lesserwhirls** [comment]
ERMAHGERD GRADLE

**Comment by lesserwhirls** [comment]
Ok, here is where I am. There is an older version of the validation-api being brought in by the gwt-gradle-plugin. Resolving the dependencies, I see it here:

```
gwtSdk - Classpath for GWT SDK libraries (gwt-dev, gwt-user)
+--- com.google.gwt:gwt-dev:2.7.0
|    +--- org.ow2.asm:asm:5.0.3
|    +--- org.ow2.asm:asm-util:5.0.3
|    |    \--- org.ow2.asm:asm-tree:5.0.3
|    |         \--- org.ow2.asm:asm:5.0.3
|    \--- org.ow2.asm:asm-commons:5.0.3
|         \--- org.ow2.asm:asm-tree:5.0.3 (*)
\--- com.google.gwt:gwt-user:2.7.0
     \--- javax.validation:validation-api:1.0.0.GA
```

I just can't seem to shake this transitive dep. If this round of tests fails, I'm not sure where to go from here.

**Comment by lesserwhirls** [comment]
(╯°□°）╯︵ ┻━┻

@cwardgar - any ideas on how to kill that transitive dep?

**Comment by cwardgar** [comment]
`./gradlew :tds:dependencies --configuration testRuntime` shows `javax.validation:validation-api:1.1.0.Final` in two places, but not the outdated version.  gwt-gradle-plugin must be doing something weird, but I'm not sure yet. It seems to be circumventing the Gradle dependency machinery that would prevent this problem in the first place.

**Comment by lesserwhirls** [comment]
Well, I think the answer is to move the changes in this commit to the
Unidata ncwms repo, let it build by itself (does not depend on tds), and do
some war overlay magic.

I'll try to give this a shot today.

**Comment by cwardgar** [comment]
I have a fix for this. I'm still not 100% comfortable with it until I find out exactly what gwt-gradle-plugin is doing, but I wouldn't spend too much time investigating the overlay magic if I were you.

**Comment by cwardgar** [comment]
So basically, gwt-gradle-plugin sucks and we shouldn't use it. It's better to just roll our own task that compiles the GWT: 1df7792cf0f0e4bea172a9c9348d8b572dcc51d5. Simply cherry-pick that commit.

**Comment by lesserwhirls** [comment]
Sweet - thanks Christian!

**Comment by lesserwhirls** [comment]
Ok, different failure this time:

```java
ucar.nc2.util.cache.ReacquireClosedDatasetSpec > classMethod FAILED
    java.lang.IllegalStateException: Timer already cancelled.
        at java.util.Timer.sched(Timer.java:397)
        at java.util.Timer.scheduleAtFixedRate(Timer.java:328)
        at ucar.nc2.util.cache.FileCache.scheduleAtFixedRate(FileCache.java:113)
        at ucar.nc2.util.cache.FileCache.<init>(FileCache.java:186)
        at ucar.nc2.dataset.NetcdfDataset.initNetcdfFileCache(NetcdfDataset.java:299)
        at ucar.nc2.dataset.NetcdfDataset.initNetcdfFileCache(NetcdfDataset.java:284)
        at ucar.nc2.util.cache.ReacquireClosedDatasetSpec.setupSpec(ReacquireClosedDatasetSpec.groovy:17)
```

**Comment by cwardgar** [comment]
Are you rebased on the latest 5.0.0? I tried to fix that synchronization issue in #473. Maybe I didn't get it right.

**Comment by cwardgar** [comment]
Nevermind, I've verified that your branch has that commit. Shit. Back to the drawing board on that one.

**Comment by rsignell-usgs** [comment]
green light baby! woo hoo!

**Pull request merged**
