### PR TITLE
grib collection tests

### PR DESCRIPTION
**Pull request by JohnLCaron**

### CODE REVIEW

**Comment by JohnLCaron** [comment]
Strange that openjdk fails and oraclejdk succeeds. What could cause that??

**Comment by lesserwhirls** [comment]
That is really odd. For example, I see `ucar.nc2.grib.collection.TestGrib2Collection` `testGFS_2p5deg` failed on openjdk, but not oraclejdk. I see things like this on the openjdk run:

~~~
reading/Creating gbx9 index for file ../grib/src/test/data/collection/grib2/ens/GEFS_Global_1p0deg_Ensemble_20141206_0600.grib2.gbx9 failed
~~~

Does that indicate that we're trying to create an index file for an index file?

**Comment by JohnLCaron** [comment]
When Grib.debugGbxIndexOnly is true, that means use the gbx9 files without requiring the data files to be present (eg see Grib1CollectionBuilder line 72). So the error message is slightly misleading, but I think it should have worked.

It seems fishy, maybe a bug in Travis about getting new data files copied? Hard to tell without being able to get it in the debugger. Do you know how to set the logging level in Travis?

**Comment by lesserwhirls** [comment]
Ok, so this is interesting. I downloaded the same JDK (openjdk 8u141), but on Windows, and the tests pass...however...I get flip-flop behavior each time I run one of the tests. The first time I run `ucar.nc2.grib.collection.TestGrib1Collection,testRdvamds083pofp`, I get:

~~~java
"C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.141-2\bin\java.exe"...
ucar.nc2.grib.collection.TestGrib1Collection,testRdvamds083pofp
changed = true
 ds083.2_pofp#MRUTP type=GRID
~~~ 

but if I run it again, I get:

~~~java
"C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.141-2\bin\java.exe"...
ucar.nc2.grib.collection.TestGrib1Collection,testRdvamds083pofp
[17:00:52.940 WARN  u.n.g.collection.TestGrib1Collection] Error making partition ..\grib\src\test\data\collection\grib1\pofp\2004 'No files in this collection =ds083.2_pofp-2004 topdir=..\grib\src\test\data\collection\grib1\pofp\2004'
[17:00:52.947 WARN  u.n.g.collection.TestGrib1Collection] Error making partition ..\grib\src\test\data\collection\grib1\pofp\2005 'No files in this collection =ds083.2_pofp-2005 topdir=..\grib\src\test\data\collection\grib1\pofp\2005'
[17:00:52.981 WARN  u.n.g.collection.TestGrib1Collection] Error making partition ..\grib\src\test\data\collection\grib1\pofp 'Nothing in this partition =name=ds083.2_pofp directory=..\grib\src\test\data\collection\grib1\pofp'
changed = false
 ds083.2_pofp#MRUTP type=GRID
~~~

Notice that the we go from `changed = true` to `changed = false`. If I run it again, and I'm back to the first message, and the pattern repeats. This behavior does not depend on which JDK I use either. Maybe it's a clue?

**Comment by lesserwhirls** [comment]
In terms of logging (sorry I missed that), it looks like each module has a `<module>/src/test/resources/logback-test.xml` config that allows you to control logging for a given module (all `ConsoleAppender`s at `WARN` level). As long as we revert changes to those during the final merge into 5.0, you could add a temporary commit that turns up the logging where needed and see what pops out.

**Comment by JohnLCaron** [comment]
flip-flop sounds right, ill check it out. thanks

**Comment by JohnLCaron** [comment]
Cant reproduce the problem on my local machine.
One thing that occurs to me, Travis may be running tests in parellel. The grib collection test are relying on a global setting:

Grib.setDebugFlags(new DebugFlagsImpl("Grib/debugGbxIndexOnly"));

very bad dog. Im going to withdraw these tests for now.

**Pull request closed without merging**
