### PR TITLE
Nullable

### PR DESCRIPTION
**Pull request by JohnLCaron**
Grib cleanup - Use Nullable and clean up use of nulls.

### CODE REVIEW

**Comment by JohnLCaron** [comment]
This one has some real effects on the code, so need to check unit tests.

**Comment by lesserwhirls** [comment]
Running on Jenkins now

**Comment by JohnLCaron** [comment]
There are 16 failing Jenkins tests.
The last 8 are failing on the main branch.
I think I just fixed 4 of them due to CalanderData.UNKNOWN (see latest commit).
4 more are failing due to Issue #1230, and not due to this PR:
  NDFD-CONUS-5km
  rdaTest/ds094.2_dt
This needs to be fixed separately.

Need another Jenkins run to verify this.
We should also fix the 8 failures on the main branch.

**Comment by lesserwhirls** [comment]
Ran on Jenkins and indeed four of the tests started passing. Merging.

**Pull request merged**
