### PR TITLE
Enable NcML written in TDS config catalogs to be opened as a FeatureDatasetCoverage

### PR DESCRIPTION
**Pull request by lesserwhirls**
Fixes the issue where WCS service did not work for NcML, as reported on the THREDDS mailing list.

### CODE REVIEW

**Comment by cwardgar** [comment]
Can you add a test for this?

**Comment by lesserwhirls** [comment]
I will. I found an issue with our ChronicleMap dataset tracker that might cause some issues, so let me fix that one first.

**Comment by lesserwhirls** [comment]
So this PR really needs Unidata/thredds/pull/1011 first, otherwise you have to remove the dataset tracker database every time you restart the TDS. Once that goes in, I will write a test and update this PR.

**Comment by lesserwhirls** [comment]
Ok, this should be ready to review as long as travis passes.

**Comment by cwardgar** [comment]
So you didn't need to add a `serviceName` for WCS to the catalog?

**Comment by lesserwhirls** [comment]
I was able to switch [this](https://github.com/Unidata/thredds/pull/1010/files#diff-ffa9afb62a6f8f764317c4f0f7ff8225R172) one to use `serviceName=all`, which includes wcs. However, that agg was sort of broken before, so I also had to fix the `DiskCache` path in [threddsConfig.xml](https://github.com/Unidata/thredds/pull/1010/files#diff-e765faf390d844eea8fec203b3619f89L90).

**Comment by cwardgar** [comment]
Ah, okay. Make sense.

**Pull request merged**
