### PR TITLE
add informative message when FMRC is empty

### PR DESCRIPTION
**Pull request by lesserwhirls**
fixes Unidata/thredds#705

### CODE REVIEW

**Comment by lesserwhirls** [comment]
I don't like the result of this though. The runtime error message collides with the TDS IOException and it reads a bit...funny.

**Comment by cwardgar** [comment]
It collides with IOException? I see it being wrapped and rethrown as an IOException in `FeatureCollectionCache.makeFeatureCollection()`, if that's what you mean. Definitely some weirdness happening there.

Also, if possible, the exception would be more useful if it included the scan location and regex.

**Comment by lesserwhirls** [comment]
I think that's ok, but because of `TdsErrorHandling.handle(IOException ex)`, we get the text "IOException sending File" added to the message, so this is what we get in the browser:

`IOException sending File java.lang.RuntimeException: The FMRC GFS_0.25_degreecannot find any files in the collection.`

It just reads funny.

I'll look at adding the addition info as well.

**Comment by lesserwhirls** [comment]
Ok, I've logged the specific info rather than displaying file system info in the browser message. The message looks like:

`[2016-12-07T17:53:24.155-0500] WARN  thredds.featurecollection.InvDatasetFcFmrc: The FMRC GFS_0.25_degree defined in /thredds/catalog/catalogs/exampleFmrc.xml cannot find any files matching the spec /Users/sarms/dev/unidata/content/5.0/thredds/public/testdata/GFS_Global_0p25deg_#yyyyMMdd_HHmm#\.grib2\.nc4$.`

**Comment by cwardgar** [comment]
That message looks good to me. Your diff went crazy though. I wonder why that happens? I've seen it with commits from Dennis as well. Some boring whitespace issue, most likely.

If you know what caused it and can fix it easily, I'd appreciate it, so that we can keep our history nice. If not, no sweat; I'll just merge.

**Comment by lesserwhirls** [comment]
Yeah, I can fix that. I had IntelliJ reformat the code without thinking,
which I do on all new files I create. I'll update here in a bit.

**Comment by lesserwhirls** [comment]
much better :-)

**Comment by cwardgar** [comment]
Lovely.

**Pull request merged**
