### PR TITLE
Added "Netcdf4Clibrary.useForReading" property to threddsConfig.xml

### PR DESCRIPTION
**Pull request by cwardgar**
* Also added it to nj22Config.xml.
* Added HTML documentation for the property.
* Added property to the default threddsConfig.xml.
* Improved several log messages.
* Nuked threddsConfig.xml.txt. We now just link to the default threddsConfig.xml on GitHub.

### CODE REVIEW

**Comment by cwardgar** [comment]
This enables a workaround for the problem identified in #518. I will follow with a PR on 5.0.0 that has AsciiDoc changes that mirror the HTML changes I made in this.

**Comment by dblodgett-usgs** [comment]
👍 If there's a built war some place I can use to test, I'm ready to try it out on our production-scale data.

**Comment by lesserwhirls** [comment]
Thanks @cwardgar!

@dblodgett-usgs - you can grab the latest snapshot war here:

https://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/edu/ucar/tds/4.6.6-SNAPSHOT/tds-4.6.6-20160608.175934-6.war

Just remember to rename is to thredds##4.6.6-SNAPSHOT.war before deploying.

**Comment by dblodgett-usgs** [comment]
Maybe I'm doing something wrong. Is that context path critical? I'm getting a lot of ` java.io.IOException: java.io.IOException: 2: No such file or directory ` then way down the stack...

```
Caused by: java.io.IOException: 2: No such file or directory
	at ucar.nc2.jni.netcdf.Nc4Iosp._open(Nc4Iosp.java:317)
```
For any ncml aggregation I try that uses netcdf4 files.

**Comment by cwardgar** [comment]
Strange, I cannot reproduce the problem. `barf.sh` from #518 even works for me.

I wonder if netcdf is installed properly. Do the command-line tools such as `ncdump` work for you? Did you build it from source or install it via a package manager? @lesserwhirls Didn't we decide that the netcdf libs that are available from package managers are unsuitable for NetCDF-Java and that it's necessary to build from source? I forget why.

**Comment by lesserwhirls** [comment]
You need to build a threads safe version of HDF5, and make sure netCDF-C
links to that.

For more info, see the section "A note on HDF5" here:

http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/netcdf4Clibrary.html

**Comment by dblodgett-usgs** [comment]
I'm checking with our SA who built it originally. I would bet it's not thread safe. It does appear to work with single files at a time.

**Comment by dblodgett-usgs** [comment]
We got it built with threads-safe enabled and I still have the issue. 

Turns out it is isolated to aggregations that declare the members of the aggregation by path rather than using a scan. We use that pattern a lot. 

ie.
This does not work:
```
<?xml version="1.0" encoding="UTF-8"?>
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
        <aggregation type="joinExisting" dimName="time">
                <netcdf location="prism_1890-1899.nc" />
                <netcdf location="prism_1900-1909.nc" />
                <netcdf location="prism_1910-1919.nc" />
...
        </aggregation>
</netcdf>
```
this does:
```
<?xml version="1.0" encoding="UTF-8"?>
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
        <aggregation type="joinExisting" dimName="time">
                <scan location="./" suffix=".nc" subdirs="false"/>
        </aggregation>
</netcdf>
```

I'd really rather not convert everything to scans...

**Comment by cwardgar** [comment]
Okay, I think I have an idea about this. It's probably some stupid issue wrt passing relative paths to the C library. I think I can fix it by just passing absolute paths.

**Comment by cwardgar** [comment]
Fixed in #560. [Here](http://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/edu/ucar/tds/4.6.6-SNAPSHOT/tds-4.6.6-20160609.222655-8.war) is a new build of TDS.

**Comment by dblodgett-usgs** [comment]
That appears to have done it.

**Comment by cwardgar** [comment]
Awesome. Any hiccups at all with the latest build?

**Comment by dblodgett-usgs** [comment]
Haven't had enough chance to push on it. Aggregations seem slow to unresponsive for really big ones, but that could be something else... Need to investigate more. 

On June 10, 2016 1:41:09 PM EDT, Christian W <notifications@github.com> wrote:
>Awesome. Any hiccups at all with the latest build?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Unidata/thredds/pull/558#issuecomment-225247779

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dblodgett-usgs** [comment]
I don't see in the docs, does THREDDS use of NetCDF4 require the parallel option to be turned on?  

I'm tracking down two issues... one where the server completely hangs on normal catalog.html type requests while under load, and another where some aggregations are producing a null pointer that is swallowed so the in-flight request just never comes back. Will do some more looking and get back to you.

**Comment by cwardgar** [comment]
No, THREDDS does not require that libnetcdf be compiled with Parallel I/O Support. I'm actually not sure whether THREDDS would even benefit from that, but I know we don't use it on our production machines.

It looks like you have some remaining issues to troubleshoot, but they seem unrelated to `Netcdf4Clibrary.useForReading`. So, I'm gonna go ahead and cut a v4.6.6 release that includes that feature tomorrow.

**Comment by dblodgett-usgs** [comment]
OK, yeah. I think the issues I'm seeing may be related to a difference in performance between the C library and the native HDF library. I'm continueing to bang on it. 

I'm getting really poor aggregation performance, and the caches don't seem to be getting used. It's rescanning big aggregations every time I come back to them. 

I think I'll just have to rewrite these data into monolothic joined-together files. If it turns out that performance of the C approach is worse, I don't think we'll want to use it, unfortunately. Will keep you posted with findings.

**Pull request merged**
