### PR TITLE
take into account 401 and 403 HTTP codes. Fix Unidata/thredds#551

### PR DESCRIPTION
**Pull request by cofinoa**
The 403 HTTP response status code is considered as IOException like 401 HTTP response. 
Also the exception message include the return status code.

### CODE REVIEW

**Comment by DennisHeimbigner** [comment]
I have a fixed branch, but I am waiting until 
tests like thredds.tds.TestRestrictDataset
have been fixed in 5.0.0

**Comment by lesserwhirls** [comment]
Thanks @DennisHeimbigner!

**Comment by cwardgar** [comment]
`TestRestrictDataset` is fixed in #733, FYI. It's awaiting review.

**Comment by DennisHeimbigner** [comment]
This also fixes, I think,  pr 625,and  pr 547.
pr 552 should be accepted just before this pr.

**Comment by cwardgar** [comment]
> pr 552 should be accepted just before this pr.

I'm confused: this page **is** PR 552.

Doesn't look like this PR can be merged easily. Can you port its changes so that we can close this and the other PRs?

**Comment by DennisHeimbigner** [comment]
Wait, what happened to the authtoforbid.dmh branch pull request?
Now I am confused also. I will build a new branch and pr that
also incorporates this pr (552).

I had intended my pr to be based off of 5.0.0; should I be basing off of master?

**Comment by DennisHeimbigner** [comment]
oops, looks like this was already fixed in pr 754.

**Comment by DennisHeimbigner** [comment]
Super-ceded by pr 754

**Pull request closed without merging**
