### PR TITLE
Fix time interval name string construction

### PR DESCRIPTION
**Pull request by lesserwhirls**
Fixes Unidata/thredds#854

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Need to do a full Jenkins run before considering this one.

**Comment by lesserwhirls** [comment]
Nope...will update with something better.

**Comment by JohnLCaron** [comment]
Theres a bunch of work on 5.0 with regards to time interval grib naming.
Also, the issues are convoluted, and in some cases the results are unexpected.
Would be glad to review issues on current version of 5.0. 
4.6, not so much.

**Comment by lesserwhirls** [comment]
Yes, from what I recall, the way time units (and perhaps time info more generally) are handled between GRIB1 and GRIB2 are not consistent. I've been meaning to get back to these issues, but if you see any you'd like to take a stab at on 5, then 👍 . I'm also happy to get you an account on Jenkins again if you'd like to be able to run the full test suite. In terms of GRIB, in my ideal world, 4.6 will likely get one more table refresh and that's it (actually, in my ideal world, 4.6 would be long gone).

**Pull request closed without merging**
