### PR TITLE
Add SonarScan to Travis-CI build

### PR DESCRIPTION
**Pull request by lesserwhirls**
Note that the conf file is not located in the TLD of the project.
The conf file is located in travis/sonar-scanner/conf

### CODE REVIEW

**Comment by lesserwhirls** [comment]
I think Travis needs to be kicked-off by the Unidata/thredds account, so the sonarqube analysis will likely fail this time, but hopefully work when merged.

**Comment by cwardgar** [comment]
It'll be tricky to merge this in, what with it causing Travis to fail.

This seems like it might be a little heavy-weight to be run for every PR. How long does a scan take? Should we be doing this as a nightly job on Jenkins instead?

**Comment by lesserwhirls** [comment]
It would be easy to add as a nightly job on Jenkins - let's just do that.
Cloud instance of Jenkins?

**Comment by lesserwhirls** [comment]
...and of course, there is a cradle plugin for this!

**Comment by cwardgar** [comment]
Yeah, the cloud instance. I'm doing a bunch of Gradle work right now, so I can go ahead look into the Sonar Gradle plugin if you want.

**Comment by lesserwhirls** [comment]
Here is the info on the gradle plugin:

http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Gradle

I could not get it to work, but you are the gradle guru! If you can't get
it to work, we'll just go with the command line stuff. Let me know if you
need any info on the appropriate settings and config options.

Thanks!

**Comment by cwardgar** [comment]
I have Sonar working with the plugin. Here's a preview: https://sonarqube.com/dashboard/index/edu.ucar:thredds

There's a lot of config that needs to be done though. I'll work on that.

**Comment by lesserwhirls** [comment]
Nice! Well done man!

**Comment by DennisHeimbigner** [comment]
This may be useful; it shows some ways to suppress warning on selected pieces of code.
https://groups.google.com/d/msg/sonarqube/szJ7EXbevHk/EdiyyUdHAwAJ

**Comment by cwardgar** [comment]
Superseded by #652.

**Pull request closed without merging**
