### PR TITLE
Add S3 And HDFS RandomAccessFile Implementations

### PR DESCRIPTION
**Pull request by jamesmcclain**
This pull request adds S3 and HDFS `RandomAccessFile` implementations so that files can be read from those two sources.

There appear to be at least three general categories of files: completely uncompressed (e.g. `testWrite.nc`), compressed with some utility (e.g. `https://noaa-nexrad-level2.s3.amazonaws.com/1991/07/20/KTLX/KTLX19910720_160529.gz`), and compressed as part of the file format (e.g. `s3://noaa-nexrad-level2/2017/01/01/KTLX/KTLX20170101_235925_V06`).  The HDFS unit tests cover all three, while the S3 unit tests only deal with the second and third.

### CODE REVIEW

**Comment by cwardgar** [comment]
Interesting work. Have you done any performance testing? I can imagine the S3 RAF being very slow for certain read patterns.

My other concern is that the AWS-S3 libraries drag in a TON of dependencies at a time when we're trying to reduce the bloat of NetCDF-Java. Maybe this addition would be more practical once we've had a chance to modularize NetCDF-Java with Project Jigsaw?

**Comment by jamesmcclain** [comment]
> Interesting work. Have you done any performance testing?

I have not.  I was initially interested in just gauging interest before putting too much time into this.

> My other concern is that the AWS-S3 libraries drag in a TON of dependencies at a time when we're trying to reduce the bloat of NetCDF-Java. Maybe this addition would be more practical once we've had a chance to modularize NetCDF-Java with Project Jigsaw?

Please take as much or as little of this work as you find useful.

As regards the question of bloat, I did make both the hadoop client library and the s3 sdk `compileOnly` so that they can be included or not included by the consumer of this code as desired.  That notwithstanding, I understand the desire to not take on too many heavy dependencies.

Please let me know if/how you would like to proceed.

**Comment by lesserwhirls** [comment]
Greetings @jamesmcclain - thank you for this work! Were you at the UCAR cafeteria yesterday, by any chance? I ask because we were talking about this exact piece of work, and after returning from lunch - boom - we see your PR!

At any rate, I think this would be an important piece of work to have included in the library, at some level. We are concerned about artifact size, but it will be some time until netCDF-Java 5 is ready for use. @cwardgar - maybe we could find a solution for artifact size before we open a beta of netCDF-Java? Maybe not include this work in the `netCDFAll.jar` artifact, but a new one?

**Comment by jamesmcclain** [comment]
> Were you at the UCAR cafeteria yesterday, by any chance? I ask because we were talking about this exact piece of work

No, but perhaps great minds think alike.

**Comment by cwardgar** [comment]
@lesserwhirls I'm not sure what you mean. Like, produce a separate fat jar that contains everything in netCDFAll *plus* the S3 and Hadoop dependencies?

**Comment by lesserwhirls** [comment]
@jamesmcclain - don't worry about the size issue. We will work that out on our end.

As for unit testing, perhaps (at least for now) it would be enough to point `S3RandomAccessFile` at one of the files that are hosted on the publicly assessable [NOAA Level II RADAR](https://data.noaa.gov/dataset/noaa-next-generation-radar-nexrad-level-ii-base-data) S3 bucket, as a smoke test at the very least. Here is a relatively small file:

https://noaa-nexrad-level2.s3.amazonaws.com/1991/07/20/KTLX/KTLX19910720_160529.gz (141 KB)

As for testing `HDFSRandomAccessFile`, I have no idea. I would not even know how to go about mocking up HDFS. Have you locally tested it?

**Comment by jamesmcclain** [comment]
Just playing around with this a little bit, I am able to read the above file when I decompress it and put it on S3, but I am not able to read a compressed version from the same bucket, so it looks like there is more work to do in that regard.  It appears to be failing somewhere in [here](https://github.com/jamesmcclain/thredds/blob/94248117bbbff323f2a37d1cad352aa31a0e024b/cdm/src/main/java/ucar/nc2/iosp/NCheader.java#L51-L98).

I would be obliged for any information that you can give in that regard.

As regards HDFS: I have tested it reading from the local file system using the HDFS machinery, but not from an actual HDFS (though I expect that it should work).

As regards testing: I put the following `build.sbt` file into some directory:
```
name := "Test"
version := "1"
scalaVersion := "2.11.8"
resolvers += Resolver.mavenLocal
libraryDependencies += "edu.ucar" % "cdm" % "5.0.0-SNAPSHOT"
libraryDependencies += "org.apache.hadoop" % "hadoop-client" % "2.7.3"
libraryDependencies += "com.amazonaws" % "aws-java-sdk-s3" % "1.11.92"
initialCommands in console += "import ucar.nc2._"
```
then I type `sbt console` and I am able to poke around.  I was able to read a file from S3 and one from the local filesystem using the HDFS machinery (by temporarily disabling the local filesystem reader) and that was the extent of my testing.

Thanks!

**Comment by jamesmcclain** [comment]
Just as an addendum: I believe that the gzip format is a stream, so I am not sure if that one is possible without downloading the entire file.  bzip2 seems to be possible.

**Comment by dopplershift** [comment]
@lesserwhirls if you pick a file from 2016, the file should be using the native bzip2 compression rather than .gz.

**Comment by jamesmcclain** [comment]
Unit tests are now included.

**Comment by jamesmcclain** [comment]
Is there anything else that needs to be done for this PR?

**Comment by lesserwhirls** [comment]
This PR looks good to me. Anyone else have any comments? If not, I will go ahead and merge this in. Again @jamesmcclain - thank you very much for your contribution! This will benefit many in the community!

**Comment by jamesmcclain** [comment]
My pleasure, thank you, sir.

**Comment by cwardgar** [comment]
Current size of the 5.0.0 fat jars:
```
-rw-r--r--  1 cwardgar  ustaff    27M May 25 10:50 ncIdv-5.0.0-SNAPSHOT.jar
-rw-r--r--  1 cwardgar  ustaff    26M May 25 10:51 netcdfAll-5.0.0-SNAPSHOT.jar
-rw-r--r--  1 cwardgar  ustaff    26M May 25 10:51 tdmFat-5.0.0-SNAPSHOT.jar
-rw-r--r--  1 cwardgar  ustaff    51M May 25 10:51 toolsUI-5.0.0-SNAPSHOT.jar
-rw-r--r--  1 cwardgar  ustaff    86M May 25 10:52 tds-5.0.0-SNAPSHOT.war
```
Size of the jars when "hadoop-client" and "s3-sdk" are added as `compile` dependencies:
```
-rw-r--r--  1 cwardgar  ustaff    65M May 25 11:09 ncIdv-5.0.0-SNAPSHOT.jar
-rw-r--r--  1 cwardgar  ustaff    68M May 25 11:10 netcdfAll-5.0.0-SNAPSHOT.jar
-rw-r--r--  1 cwardgar  ustaff    67M May 25 11:10 tdmFat-5.0.0-SNAPSHOT.jar
-rw-r--r--  1 cwardgar  ustaff    92M May 25 11:10 toolsUI-5.0.0-SNAPSHOT.jar
-rw-r--r--  1 cwardgar  ustaff   161M May 25 11:11 tds-5.0.0-SNAPSHOT.war
```
As I expected, those deps add *significant* bloat. For that reason, I think it's best to keep this feature on a separate branch for now, rather than merging it into mainline (5.0.0). We need to modularize thredds first.

**Comment by jamesmcclain** [comment]
Okay, that sounds fine.

**Comment by jamesmcclain** [comment]
I see that this PR has been redirected to a feature branch.  I do not have any immediate plans to do anything else with this PR, would you mind merging it into that feature branch?

**Comment by cwardgar** [comment]
Sure, I just wanted to make sure that you were done for now. Thanks for the contribution!

**Comment by jamesmcclain** [comment]
You are welcome.  I hope that it is/was useful.  Thank you to you and everyone else.

**Pull request merged**
