### PR TITLE
Fix NEXRAD Level 2 IOSP to work with caching. (Fixes #435)

### LINKED ISSUE #435: Problems with remote access to NEXRAD Level II data
From e-support EMY-911316
```
getSweep 
opendap.dap.DataReadException: Inconsistent array length read: 1165128303 != 1914731274; Reflectivity_HI -- 0:0,0:719,0:1831

******************
Stack trace:
java.io.IOException: opendap.dap.DataReadException: Inconsistent array length read: 1165128303 != 1914731274; Reflectivity_HI -- 0:0,0:719,0:1831
at ucar.nc2.dods.DODSNetcdfFile.readData(DODSNetcdfFile.java:1665)
at ucar.nc2.Variable.reallyRead(Variable.java:907)
at ucar.nc2.Variable._read(Variable.java:892)
at ucar.nc2.Variable.read(Variable.java:703)
at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:557)
at ucar.nc2.dataset.VariableDS._read(VariableDS.java:537)
at ucar.nc2.Variable.read(Variable.java:703)
at ucar.nc2.Variable.read(Variable.java:649)
at ucar.nc2.dt.radial.LevelII2Dataset$LevelII2Variable$LevelII2Sweep.sweepData(LevelII2Dataset.java:466)
at ucar.nc2.dt.radial.LevelII2Dataset$LevelII2Variable$LevelII2Sweep.readData(LevelII2Dataset.java:450)
at ucar.unidata.data.radar.CDMRadarAdapter.getSweep(CDMRadarAdapter.java:3540)
at ucar.unidata.data.radar.CDMRadarAdapter.getData(CDMRadarAdapter.java:1917)
at ucar.unidata.data.radar.RadarDataSource$2.run(RadarDataSource.java:531)
at visad.util.ThreadManager.runInParallel(ThreadManager.java:273)
at visad.util.ThreadManager.runInParallel(ThreadManager.java:245)
at visad.util.ThreadManager.runInParallel(ThreadManager.java:212)
at ucar.unidata.data.radar.RadarDataSource.getDataInner(RadarDataSource.java:544)
at ucar.unidata.data.DataSourceImpl.getData(DataSourceImpl.java:2390)
at ucar.unidata.data.DirectDataChoice.getData(DirectDataChoice.java:332)
at ucar.unidata.data.DataChoice.getData(DataChoice.java:637)
at ucar.unidata.data.DataInstance.getData(DataInstance.java:243)
at ucar.unidata.data.DataInstance.getData(DataInstance.java:207)
at ucar.unidata.data.grid.GridDataInstance.init(GridDataInstance.java:206)
at ucar.unidata.data.grid.GridDataInstance.<init>(GridDataInstance.java:163)
at ucar.unidata.data.grid.GridDataInstance.<init>(GridDataInstance.java:144)
at ucar.unidata.idv.control.GridDisplayControl.doMakeDataInstance(GridDisplayControl.java:293)
at ucar.unidata.idv.control.RadarSweepControl.doMakeDataInstance(RadarSweepControl.java:296)
at ucar.unidata.idv.control.DisplayControlImpl.initializeDataInstance(DisplayControlImpl.java:3278)
at ucar.unidata.idv.control.DisplayControlImpl.setData(DisplayControlImpl.java:3234)
at ucar.unidata.idv.control.PlanViewControl.setData(PlanViewControl.java:664)
at ucar.unidata.idv.control.RadarSweepControl.setData(RadarSweepControl.java:114)
at ucar.unidata.idv.control.PlanViewControl.init(PlanViewControl.java:489)
at ucar.unidata.idv.control.RadarSweepControl.init(RadarSweepControl.java:158)
at ucar.unidata.idv.control.DisplayControlImpl.init(DisplayControlImpl.java:1402)
at ucar.unidata.idv.control.DisplayControlImpl.init(DisplayControlImpl.java:1085)
at ucar.unidata.idv.ControlDescriptor.initControl(ControlDescriptor.java:986)
at ucar.unidata.idv.ControlDescriptor$1.run(ControlDescriptor.java:911)
at ucar.unidata.util.Misc$3.run(Misc.java:1243)
```

I can reproduce easily. Local file opens fine (including ncdump of data using ToolsUI). Opendap and CDMRemote (from both ToolsUI and Python) fail....all with different messages.

### PR DESCRIPTION
**Pull request by dopplershift**
The underlying problem was readData using the raf from the internal volScan object rather than the raf that gets properly initialized when the netcdffile was reloaded from cache.

There is absolutely no reason for volScan to be a class attribute, so convert it to a local variable, and pass it as needed to other functions. This technically changes the function def of a public function, so I've added an overload to make sure things stay compatible for 4.6 (just in case). This also eliminates a private internal function that was making use of the attribute.

### CODE REVIEW

**Comment by dopplershift** [comment]
Thanks for @cwardgar for walking through this with me to identify the relatively simple fix.

**Comment by lesserwhirls** [comment]
Awesome job @cwardgar and @dopplershift! I'll get this merged in and up on thredds asap.

**Comment by dopplershift** [comment]
Wait for confirmation from me....I may not have gotten everything right in the commit...

**Comment by lesserwhirls** [comment]
Ok, I'll wait for the bat signal @dopplershift - thanks again!

**Comment by dopplershift** [comment]
We're good. (I got crossed up and had forgotten I'd switched back to master when I went to sanity check.)

**Comment by dopplershift** [comment]
And just for reference, I can only trace the problematic code back to 2006, when @ethanrd imported a whole bunch of code. Who knows who the guilty party really is... :imp:

**Comment by dopplershift** [comment]
Um, Travis doesn't even show this PR yet...

**Comment by lesserwhirls** [comment]
Travis says...

Travis says..."

...although it is a bit unnerving that it has not shown up yet.

**Comment by lesserwhirls** [comment]
Ok, I think travis is not going to run this...I merged Dennis' PR - would you mind rebasing? Maybe that will trigger a travis run?

**Comment by dopplershift** [comment]
Done. It looks like Travis has decided to run this one.

**Pull request merged**
