### PR TITLE
Add License Gradle Plugin

### PR DESCRIPTION
**Pull request by lesserwhirls**

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Adds the [license-gradle-plugin](https://github.com/hierynomus/license-gradle-plugin)

To generate a license report, run

`./gradlew downloadLicense`

and look in the `build/reports/license/` directory for the report.

There are many tweaks that can be done - this is just the basics.

@cwardgar - does this look properly integrated into our build system?

**Comment by cwardgar** [comment]
I added a small commit that limits application of license.gradle to rootProject. Otherwise looks good.

**Comment by cwardgar** [comment]
Also, it's crazy that I can edit your PR directly in GitHub and have the commit appear in your repo.

**Comment by dopplershift** [comment]
When you submit a PR, there's an option on the PR to allow project maintainers (i.e. those with write access to the main project) to make changes; it's a nice and easy way to allow us to rebase contributed fixes, for instance.

**Pull request merged**
