### PR TITLE
Merge master into 5.0

### PR DESCRIPTION
**Pull request by lesserwhirls**
Includes changes through 4.6.11 release as well as unidata/thredds#970 and unidata/thredds#972

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Failed because on `5.0.0` we test reading a `cdf-5` file through the `netCDF-C` library, but we didn't compile the updated `4.5` version with `cdf-5` support (`--enable-cdf5`). @cwardgar will rebuild the `netCDF-C` library with `cdf5` support enabled and commit those changes to `master`. I will do another rebase of `master` into `5.0.0` and update this PR to include it. Then, we all have 🍻 (`--enable-beer`)

**Comment by lesserwhirls** [comment]
fingers crossed!

**Comment by cwardgar** [comment]
Yay! I'm gonna go ahead and merge this. If it causes problems for tests on Jenkins, we'll know soon enough.

**Comment by cwardgar** [comment]
EDIT: Nevermind, already merged. Page was out of date!

**Pull request merged**
