### PR TITLE
workaround for the issue #90 ( HTTPSSLProvider is not working )

### PR DESCRIPTION
**Pull request by cofinoa**
This is a workaround for the issue #90

### CODE REVIEW

**Comment by cwardgar** [comment]
Try creating a pull request against Unidata:4.5.4, not Unidata:4.5.3.

**Comment by DennisHeimbigner** [comment]
This is probably a result of our moving to Apache httpclient library 4.2.
I have not had the capability of testing the client side keys issue.

**Comment by cofinoa** [comment]
I made this pull-request against the wrong branch and therefore @cwardgar has closed it.
I have create a new pull request against the 4.5.4 branch. The pull-request is the #92

**Comment by DennisHeimbigner** [comment]
It turns out that equivalent code is already in 4.5.5 and 4.6.0.
You can see it at HTTPSession#setGlobalKeystore().
However, the invocation of this code in HTTPAuthStore has a bug
that prevented it from being invoked.  I have fixed 4.5.5. to invoke the
code properly. However, I still do not know if it works because
of no access to a server to test it.  Please pull 4.5.5 from github
and see if it solves your problem.

**Pull request closed without merging**
