### PR TITLE
Update script.sh

### PR DESCRIPTION
**Pull request by lesserwhirls**

### CODE REVIEW

**Comment by lesserwhirls** [comment]
So this one we should actually merge, as we no longer are building docs using asciidoctor. The others are just tests and can be closed.

**Comment by cwardgar** [comment]
Any reason you're commenting-out instead of deleting? And what about the `adoc2html.sh` file?

**Comment by lesserwhirls** [comment]
Uh...umm...that was a test? Yeah, that's it! It was a test! See, reviews work. Yay. Super good job #1. 👍 👍 👍 💯

**Comment by cwardgar** [comment]
Travis is being dumb.

**Comment by lesserwhirls** [comment]
I think I may need to open a new PR...

**Pull request closed without merging**
